// Help entries for the info panel, English and Czech.
// Fields: key, title, what it does, how it works, try this, reference.

#include "ui/Strings.h"

#include <unordered_map>

namespace sph::ui
{
namespace
{
struct T
{
    const char* en;
    const char* cs;
};

struct Entry
{
    const char* key;
    T title, what, how, tryThis;
    const char* ref;
};

const Entry entries[] = {
// ---------------------------------------------------------------- global
{ "p.engine",
  { "Engine", "Jádro (Engine)" },
  { "Chooses the analysis: Light runs with no latency, Full analyses the spectrum and adds one FFT frame of latency.",
    "Volí analýzu: Lehké běží bez latence, Plné analyzuje spektrum a přidává latenci jednoho rámce FFT." },
  { "Full splits the sound into tonal, noise and transient parts and tracks individual partials. That enables the Pan map, the coherence designer, the image expander and the spectral sources. Your host compensates the latency automatically.",
    "Plné jádro rozkládá zvuk na tónovou, šumovou a přechodovou složku a sleduje jednotlivé parciály. Teprve tak fungují panoramatická mapa, návrhář koherence, rozšíření stereobáze a spektrální zdroje. Latenci hostitel vyrovná automaticky." },
  { "Switch to Full and watch the latency readout: it shows exactly one frame (about 43 ms at 48 kHz).",
    "Přepněte na Plné a sledujte údaj latence: ukazuje přesně jeden rámec (asi 43 ms při 48 kHz)." },
  "Short-time Fourier analysis; Fitzgerald 2010 (median filtering)" },
{ "p.width",
  { "Width", "Šíře (Width)" },
  { "Master level of the synthesised side signal.", "Celková úroveň syntetizovaného bočního signálu." },
  { "Every generator adds to the side (L - R) only. Width scales that sum before the correlation guard. The mid (L + R) is never touched, so the mono sum stays identical at any width.",
    "Všechny generátory přispívají jen do strany (L - R). Šíře tento součet škáluje ještě před hlídačem korelace. Střed (L + R) zůstává nedotčen, takže mono součet je při jakékoli šíři stejný." },
  { "Set Listen to Mono and turn Width: nothing changes. That is mono compatibility.",
    "Přepněte Poslech na Mono a otáčejte Šíří – nic se nezmění. To je mono kompatibilita." },
  "Blumlein 1931 (M/S); Gerzon 1992" },
{ "p.mid_blend",
  { "Mid blend", "Příměs středu (Mid blend)" },
  { "Adds each generator's mid component back, for its authentic, non-mono-safe sound.",
    "Vrací do středu složku každého generátoru – pro jeho původní zvuk, který ale není mono-kompatibilní." },
  { "At 0 % only the side is synthesised and the mono sum equals the input. At 100 % the Haas delay becomes a true L = dry, R = delayed pair, and the chorus or doubler is heard in mono too, with the comb colouring that implies.",
    "Při 0 % se syntetizuje jen strana a mono součet se rovná vstupu. Při 100 % se z Haasova zpoždění stane skutečný pár L = suchý, R = zpožděný a chorus či zdvojení je slyšet i v mono – včetně hřebenového zabarvení." },
  { "Load Classic: Haas, then switch Listen to Mono: the comb filter you hear is why mono-safe mode exists.",
    "Načtěte Klasika: Haas a přepněte Poslech na Mono: hřebenový filtr, který uslyšíte, je důvod, proč existuje mono-kompatibilní režim." },
  "Haas 1951; Schroeder 1958" },
{ "p.bass_mono_hz",
  { "Bass mono", "Mono basy (Bass mono)" },
  { "High-passes the side so that bass stays centred.", "Odfiltruje basy ze strany, takže zůstanou uprostřed." },
  { "A 24 dB/octave Linkwitz-Riley high-pass on the synthesised side. Low frequencies carry most of the energy and are hard to localise, so wide bass mostly costs headroom and translates badly to vinyl, clubs and phones. At 20 Hz the filter is off.",
    "Horní propust Linkwitz-Riley 24 dB/okt. na syntetizované straně. Nízké kmitočty nesou nejvíc energie a špatně se lokalizují, takže široké basy hlavně ubírají rezervu a špatně se přenášejí na vinyl, do klubu i do telefonu. Při 20 Hz je filtr vypnutý." },
  { "Solo the side with Listen: Side, then raise Bass mono: the low end disappears from the side only.",
    "Poslechněte jen stranu (Poslech: Strana) a zvyšujte Mono basy: hloubky zmizí jen ze strany." },
  "Linkwitz and Riley 1976" },
{ "p.band_xover_lo",
  { "Crossover low", "Dělicí kmitočet dolní" },
  { "Boundary between the low and mid width bands.", "Hranice mezi pásmem basů a středů pro šíři." },
  { "The side is split into three bands with Linkwitz-Riley crossovers that sum flat, so each band's width can be set on its own.",
    "Strana se dělí na tři pásma výhybkami Linkwitz-Riley, které se sčítají rovně, takže šíři každého pásma lze nastavit zvlášť." },
  { "Set Low width to 0 % and sweep this crossover: you move where the image starts to open up.",
    "Nastavte šíři basů na 0 % a pohybujte dělicím kmitočtem: posouváte místo, kde se obraz začíná rozevírat." },
  "Linkwitz and Riley 1976" },
{ "p.band_xover_hi",
  { "Crossover high", "Dělicí kmitočet horní" },
  { "Boundary between the mid and high width bands.", "Hranice mezi pásmem středů a výšek pro šíři." },
  { "Together with the low crossover it defines three side bands whose widths are set below.",
    "Spolu s dolním dělicím kmitočtem určuje tři boční pásma, jejichž šíři nastavíte níže." },
  { "Push High width to 150 % and lower this crossover to hear the air move outward.",
    "Zvyšte šíři výšek na 150 % a snižujte tento kmitočet – uslyšíte, jak se vzduch posouvá do stran." },
  "Gerzon 1992 (frequency-dependent width)" },
{ "p.band_low", { "Low width", "Šíře basů" }, { "Width of the side below the low crossover.", "Šíře strany pod dolním dělicím kmitočtem." },
  { "Scales the low band of the synthesised side. Narrow lows keep the mix solid while the upper bands open up.",
    "Škáluje dolní pásmo syntetizované strany. Úzké basy drží mix pevný, zatímco vyšší pásma se otevírají." },
  { "Compare 0 % and 100 % on a bass-heavy source with Listen: Side.", "Porovnejte 0 % a 100 % na zdroji s výraznými basy při poslechu strany." }, "Gerzon 1992" },
{ "p.band_mid", { "Mid width", "Šíře středů" }, { "Width of the side between the crossovers.", "Šíře strany mezi dělicími kmitočty." },
  { "Vocals and most instruments live here; this band decides how wide the 'body' of the mix feels.",
    "Tady leží zpěv a většina nástrojů; toto pásmo rozhoduje, jak široké se zdá „tělo“ mixu." },
  { "Lower it slightly when the centre of a mix feels hollow.", "Mírně ji snižte, když střed mixu zní dutě." }, "Gerzon 1992" },
{ "p.band_high", { "High width", "Šíře výšek" }, { "Width of the side above the high crossover.", "Šíře strany nad horním dělicím kmitočtem." },
  { "High frequencies are localised by level differences and give the clearest sense of space, so a little extra width here goes a long way.",
    "Vysoké kmitočty se lokalizují podle rozdílů úrovně a dávají nejzřetelnější dojem prostoru – trocha šíře navíc tu udělá hodně." },
  { "Try 130 % with Low at 50 %: the classic shaped spread.", "Zkuste 130 % a basy na 50 %: klasické tvarované rozprostření." }, "Gerzon 1992" },
{ "p.transient_duck",
  { "Transient duck", "Útlum transientů (Transient duck)" },
  { "Narrows the synthesised side on attacks, so drums and plucks stay centred and punchy.",
    "Na náběhy zužuje syntetizovanou stranu, takže bicí a drnkání zůstanou uprostřed a s důrazem." },
  { "A detector finds onsets (in the Full engine from the spectral flux, with 2 ms of lookahead) and briefly turns the side down, then lets it recover over about 100 ms. Decorrelators smear attacks; ducking keeps them crisp.",
    "Detektor hledá nástupy (v plném jádru ze spektrálního toku s předstihem 2 ms) a krátce ztlumí stranu, kterou pak během asi 100 ms vrátí. Dekorelátory náběhy rozmazávají; útlum je udrží ostré." },
  { "Use the Tone and click teaching source and watch the duck lane in Scopes.", "Použijte výukový zdroj Tón a klik a sledujte stopu útlumu v Průbězích." },
  "Bello et al. 2005 (onset detection); Breebaart et al. 2005" },
{ "p.guard",
  { "Correlation guard", "Hlídač korelace (Guard)" },
  { "Keeps the synthesised side no louder than the mid, so the correlation never goes negative.",
    "Drží syntetizovanou stranu nanejvýš tak hlasitou jako střed, takže korelace nikdy neklesne pod nulu." },
  { "Negative correlation means the channels partly cancel: phasey, unstable images that vanish in mono. The guard measures mid and side power over 200 ms and turns the side down when it would exceed the mid.",
    "Záporná korelace znamená, že se kanály částečně ruší: fázově nestabilní obraz, který v mono zmizí. Hlídač měří výkon středu a strany za 200 ms a stranu ztlumí, kdyby měla střed překročit." },
  { "Push Width to 200 % and toggle the guard while watching the correlation meter.", "Dejte Šíři na 200 % a přepínejte hlídač, přitom sledujte korelační měřič." },
  "IEC 60268-18 (correlation meters)" },
{ "p.guard_ceiling_db",
  { "Guard ceiling", "Strop hlídače" },
  { "How loud the side may get against the mid before the guard turns it down.",
    "Jak hlasitá smí být strana proti středu, než ji hlídač ztlumí." },
  { "At 0 dB the side may be as loud as the mid, which keeps the correlation at or above 0. Lower values keep it higher and limit how much louder the stereo output is: at -6 dB the side power is at most a quarter of the mid, about 1 dB of extra level. Easy mode uses -6 dB.",
    "Při 0 dB smí být strana stejně hlasitá jako střed, což drží korelaci na nule nebo výš. Nižší hodnoty ji drží výš a omezují, o kolik je stereo výstup hlasitější: při -6 dB je výkon strany nanejvýš čtvrtina středu, tedy asi o 1 dB víc. Snadný režim používá -6 dB." },
  { "Set Width to 200 % and lower the ceiling while watching the correlation meter.", "Nastavte Šíři na 200 % a snižujte strop, přitom sledujte korelační měřič." },
  "IEC 60268-18 (correlation meters); ITU-R BS.1770 (loudness)" },
{ "p.ui_mode",
  { "Mode", "Režim" },
  { "Easy shows four macros; Complete shows every control.", "Snadný ukazuje čtyři makra, úplný všechny prvky." },
  { "In Easy mode the macros set the internal parameters inside the engine, so automating a macro writes no automation for them. Expanding to Complete copies the values exactly.",
    "Ve snadném režimu nastavují makra vnitřní parametry uvnitř zpracování, takže automatizace makra nezapisuje automatizaci těchto parametrů. Přechod do úplného režimu hodnoty přesně zkopíruje." },
  { "", "" }, "" },
{ "p.easy_width",
  { "Width", "Šíře (Width)" },
  { "How wide it sounds, from mono to as wide as stays mono-safe and natural.", "Jak široce to zní, od mona po nejširší obraz, který zůstane mono-kompatibilní a přirozený." },
  { "The curve was optimised so that perceived width (measured by a virtual listener at loudspeakers) rises evenly with the knob. The mono sum never changes. Percussive material reaches less width, because its hits stay centred.",
    "Křivka byla optimalizována tak, aby vnímaná šíře (měřená virtuálním posluchačem u reproduktorů) rostla s knoflíkem rovnoměrně. Mono součet se nikdy nemění. Perkusivní materiál dosáhne menší šíře, protože jeho údery zůstávají uprostřed." },
  { "Switch your host to mono, or watch the goniometer: the vertical line stays put however wide it gets.",
    "Přepněte hostitele do mono, nebo sledujte goniometr: svislá čára zůstává, ať je obraz jakkoli široký." },
  "ITU-R BS.1770; IACC after Hidaka et al. 1995" },
{ "p.easy_character",
  { "Character", "Charakter" },
  { "How the width is made: clean, diffuse or lively.", "Jak šíře vzniká: čistě, rozptýleně nebo živě." },
  { "At 0 % phase-based spreading and the coherence designer give a stable, focused image; at 50 % decorrelation (velvet noise and a virtual spaced microphone pair) gives a diffuse one; at 100 % the double-tracker and micro-pitch add the movement of two performances.",
    "Na 0 % dávají fázové rozprostření a návrhář koherence stabilní, soustředěný obraz; na 50 % dává dekorelace (sametový šum a virtuální rozložený mikrofonní pár) obraz rozptýlený; na 100 % přidají zdvojení stopy a mikrotransponování pohyb dvou výkonů." },
  { "Sweep Character with Width at 70 % and watch Under the hood.", "Projeďte Charakter při Šíři 70 % a sledujte Pod kapotou." }, "" },
{ "p.easy_space",
  { "Space", "Prostor" },
  { "Room and depth: early reflections and a wider virtual microphone pair.", "Místnost a hloubka: časné odrazy a širší virtuální mikrofonní pár." },
  { "Space raises the room cues (early reflections of a virtual room, no reverb tail), makes the room larger and the source further away, and spaces the virtual pair of the coherence designer wider apart.",
    "Prostor zesiluje prostorové odrazy (časné odrazy virtuální místnosti, bez dozvuku), zvětšuje místnost, oddaluje zdroj a rozestupuje virtuální mikrofonní pár návrháře koherence." },
  { "Try Space at 60 % on a dry vocal.", "Zkuste Prostor na 60 % na suchém zpěvu." }, "" },
{ "p.easy_focus",
  { "Focus", "Fokus" },
  { "Protects the centre: bass, hits and the low band stay mono.", "Chrání střed: basy, údery a spodní pásmo zůstávají mono." },
  { "Focus raises the bass-mono frequency (100 to 250 Hz), the transient ducking (40 to 100 %) and the coherence designer's transient protection, and narrows the low band. At 50 % hits are at least 6 dB narrower than the sound around them.",
    "Fokus zvyšuje kmitočet mono basů (100 až 250 Hz), útlum transientů (40 až 100 %) a ochranu transientů v návrháři koherence a zužuje spodní pásmo. Na 50 % jsou údery nejméně o 6 dB užší než zvuk kolem nich." },
  { "On drums, compare Focus 20 % and 80 %: the kick and snare move to the centre.", "Na bicích porovnejte Fokus 20 % a 80 %: kopák a virbl se stáhnou doprostřed." }, "" },
{ "p.easy_adapt",
  { "Adapt to material", "Přizpůsobit materiálu" },
  { "Lets the mapping follow what it hears: percussive, tonal or mixed.", "Nechá mapování sledovat, co slyší: perkusivní, tónový nebo smíšený materiál." },
  { "A classifier summarises the input into three weights that change slowly (about 2 s), and the mapping blends one set of curves per class. Off uses the mixed set always, so the mapping depends only on the macros.",
    "Klasifikátor shrne vstup do tří vah, které se mění pomalu (asi 2 s), a mapování míchá jednu sadu křivek na každou třídu. Vypnuto používá vždy smíšenou sadu, takže mapování závisí jen na makrech." },
  { "", "" }, "" },
{ "p.easy_low_latency",
  { "Low latency", "Nízká latence" },
  { "Runs without latency, without the spectral generators.", "Běží bez latence, bez spektrálních generátorů." },
  { "Easy mode normally uses the Full engine (one FFT frame of latency, 42.7 ms at 48 kHz). Low latency uses the Light engine and its own optimised curves, with velvet noise in place of the coherence designer.",
    "Snadný režim jinak používá plné jádro (latence jednoho rámce FFT, 42,7 ms při 48 kHz). Nízká latence použije lehké jádro a vlastní optimalizované křivky, se sametovým šumem místo návrháře koherence." },
  { "Use it while recording or playing live.", "Použijte ji při nahrávání nebo hraní naživo." }, "" },
{ "p.comp_mode",
  { "Compensation", "Kompenzace hlasitosti" },
  { "Mono-exact leaves levels alone; Constant loudness keeps the stereo loudness steady as width changes.",
    "Přesné mono nechává úrovně být; Stálá hlasitost drží hlasitost sterea při změně šíře." },
  { "Adding side adds energy, so wider sounds louder, which biases comparisons. Constant loudness scales both channels by sqrt(Pm / (Pm + Ps)); the mono sum keeps its spectrum but loses level, so it is no longer mono-exact.",
    "Přidaná strana přidává energii, takže širší zní hlasitěji a to zkresluje porovnávání. Stálá hlasitost škáluje oba kanály poměrem sqrt(Pm / (Pm + Ps)); mono součet si zachová spektrum, ale ztratí úroveň, takže už není přesný." },
  { "Switch to Constant loudness before judging whether wider is really better.", "Než posoudíte, zda je širší opravdu lepší, přepněte na Stálou hlasitost." },
  "ITU-R BS.1770 (loudness)" },
{ "p.out_gain_db", { "Output gain", "Výstupní zisk" }, { "Final level of both channels.", "Konečná úroveň obou kanálů." },
  { "Applied after compensation and before the meters.", "Uplatní se po kompenzaci a před měřiči." },
  { "Match levels before comparing with bypass.", "Před porovnáním s bypassem vyrovnejte úrovně." }, "" },
{ "p.listen",
  { "Listen", "Poslech (Listen)" },
  { "Audition the stereo result, the mono sum, or the side alone.", "Poslech stereo výsledku, mono součtu nebo samotné strany." },
  { "Mono plays (L + R) / 2 on both channels: what a phone speaker or a mono club system hears. Side plays (L - R) / 2: everything the plugin adds, isolated.",
    "Mono hraje (L + R) / 2 na oba kanály – to, co slyší reproduktor telefonu nebo mono ozvučení v klubu. Strana hraje (L - R) / 2 – vše, co plugin přidává, odděleně." },
  { "Flip between Stereo and Mono: with mid blend at 0 % they must sound equally full.", "Přepínejte Stereo a Mono: při příměsi středu 0 % musí znít stejně plně." },
  "" },
{ "p.bypass", { "Bypass", "Bypass" }, { "Passes the input through, delayed by the latency so it stays in time.", "Propouští vstup, zpožděný o latenci, aby zůstal v čase." },
  { "Bypass crossfades over 20 ms and keeps the alignment delay, so switching never moves the audio in time.", "Bypass prolíná 20 ms a zachovává vyrovnávací zpoždění, takže přepnutí nikdy neposune zvuk v čase." },
  { "Toggle while the transport plays: no click, no jump.", "Přepínejte během přehrávání: žádné lupnutí ani skok." }, "" },
{ "p.ambience",
  { "Ambience", "Ambience" },
  { "Moves decaying energy (room sound, tails) from the tonal to the noise component.",
    "Přesouvá doznívající energii (zvuk místnosti, dozvuky) z tónové do šumové složky." },
  { "Energy that falls the way a room's reverberation falls is treated as ambience. This lets generators on the Noise source widen the room while partials on the Tonal source stay focused.",
    "Energie, která klesá tak, jak klesá dozvuk místnosti, se považuje za ambienci. Generátory na šumovém zdroji pak rozšíří místnost, zatímco parciály na tónovém zdroji zůstanou ostré." },
  { "Route Velvet to Noise and raise Ambience on a reverberant recording.", "Pošlete Velvet na šumový zdroj a zvyšte Ambienci na nahrávce s dozvukem." },
  "Lebart, Boucher and Denbigh 2001" },
{ "p.room_decay_s", { "Room decay", "Dozvuk místnosti" }, { "Expected reverberation time for the ambience estimate.", "Očekávaná doba dozvuku pro odhad ambience." },
  { "The ambience split predicts how fast a room's energy falls; match this to the recording's reverberation.", "Rozdělení ambience předpovídá, jak rychle energie místnosti klesá; nastavte podle dozvuku nahrávky." },
  { "Longer values classify more of a tail as ambience.", "Delší hodnoty zařadí větší část dozvuku do ambience." }, "Lebart et al. 2001" },
{ "p.latency_mode",
  { "Latency mode", "Režim latence" },
  { "Per engine: Light has no latency. Always Full: both engines report one frame, so switching engine is seamless.",
    "Podle jádra: Lehké je bez latence. Vždy plná: obě jádra hlásí jeden rámec, takže přepnutí jádra je plynulé." },
  { "Changing latency mid-playback makes the host re-align tracks. With Always Full the dry signal never moves and only the Full-only parts fade in or out.",
    "Změna latence během přehrávání nutí hostitele znovu zarovnat stopy. Ve Vždy plné se suchý signál nikdy neposune a jen části plného jádra se prolnou." },
  { "Use Always Full if you automate or switch the engine during a session.", "Použijte Vždy plnou, pokud jádro během práce přepínáte." }, "" },
{ "p.transient_mode",
  { "Transient detector", "Detektor transientů" },
  { "Envelope compares a fast and a slow follower; Spectral flux looks for sudden rises across the spectrum (Full engine).",
    "Obálka porovnává rychlý a pomalý sledovač; Spektrální tok hledá náhlé nárůsty napříč spektrem (plné jádro)." },
  { "The envelope method reacts to peakiness and also ducks steady noise. Spectral flux reacts only to new energy, so steady sounds are left wide.",
    "Metoda obálky reaguje na špičatost a tlumí i ustálený šum. Spektrální tok reaguje jen na novou energii, takže ustálené zvuky zůstanou široké." },
  { "Compare both on a noisy pad with Transient duck at 100 %.", "Porovnejte obě na šumivém padu s útlumem transientů na 100 %." }, "Bello et al. 2005" },
{ "p.pan_ownership",
  { "Bin ownership", "Vlastnictví binů" },
  { "How the Pan map assigns spectrum bins between neighbouring partials: Hard to the nearest, Soft as a weighted blend.",
    "Jak panoramatická mapa přiřazuje biny spektra mezi sousedními parciály: Pevné nejbližšímu, Měkké váženou směsí." },
  { "Hard separates sources more; Soft avoids sharp pan seams between close partials.", "Pevné víc odděluje zdroje; Měkké se vyhne ostrým švům panorámy mezi blízkými parciály." },
  { "Try Soft on dense chords.", "Zkuste Měkké na hustých akordech." }, "" },
{ "p.velvet_design",
  { "Velvet design", "Návrh velvetu" },
  { "Random uses the original sequences; Optimised uses sequences tuned offline for a flat sound.",
    "Náhodný používá původní sekvence; Optimalizovaný používá sekvence vyladěné předem pro rovný zvuk." },
  { "A velvet sequence is a few dozen signed clicks. Random positions can colour the sound by many dB; the optimised tables keep every third-octave within about 2 dB and the two sides almost perfectly decorrelated.",
    "Sekvence sametového šumu je několik desítek kladných a záporných impulsů. Náhodné pozice mohou zvuk zabarvit o mnoho dB; optimalizované tabulky drží každou třetinooktávu zhruba do 2 dB a obě strany téměř dokonale dekorelované." },
  { "Switch designs with Variation set to a few different values.", "Přepínejte návrhy při několika různých variantách." },
  "Alary, Politis and Välimäki 2017; Schlecht et al. 2018" },

{ "p.width_mode",
  { "Width mode", "Režim šíře" },
  { "Manual uses the Width knob as set; Auto steers it to keep the perceived width at a target.",
    "Ručně použije knoflík Šíře, jak je nastaven; Automaticky jím pohybuje tak, aby vnímaná šíře zůstala na cíli." },
  { "Auto-width listens to its own output with the virtual listener every 100 ms and slowly adjusts the width (2 s time constant, at most 3 dB per second). Quiet, narrow passages get more width and dense, wide ones less, so the image stays even. The correlation guard still applies.",
    "Automatická šíře každých 100 ms poslouchá vlastní výstup virtuálním posluchačem a pomalu upravuje šíři (časová konstanta 2 s, nejvýš 3 dB za sekundu). Tiché úzké pasáže dostanou víc šíře, husté široké méně, takže obraz zůstane vyrovnaný. Hlídač korelace platí dál." },
  { "Set Auto, then compare a sparse verse with a dense chorus.", "Zapněte Automaticky a porovnejte řídkou sloku s hustým refrénem." },
  "Hidaka et al. 1995 (IACC); Brown and Duda 1998" },
{ "p.asw_target",
  { "Auto-width target", "Cíl automatické šíře" },
  { "The perceived width that Auto mode holds (0 = point source).", "Vnímaná šíře, kterou automatický režim drží (0 = bodový zdroj)." },
  { "Measured as on the perceived-width meter. On speakers values above about 0.55 cannot be reached because of crosstalk between the ears.",
    "Měří se stejně jako na měřiči vnímané šíře. Na reproduktorech nelze kvůli přeslechu mezi ušima dosáhnout hodnot nad asi 0,55." },
  { "0.3 is a natural, stable width.", "0,3 je přirozená, stabilní šíře." }, "" },

// ---------------------------------------------------------------- spread
{ "card.spread",
  { "Spread", "Rozprostření (Spread)" },
  { "An all-pass side signal: the classic, phase-based widener.", "Boční signál přes všepropustný filtr: klasický fázový rozšiřovač." },
  { "The side is the input through an all-pass filter, so its level is flat while its phase varies with frequency. Left and right then become complementary combs: where one has a peak, the other has a dip, and their powers always add up flat.",
    "Strana je vstup přes všepropustný filtr – úroveň má rovnou, ale fáze se mění s kmitočtem. Levý a pravý kanál se pak stanou doplňkovými hřebeny: kde má jeden vrchol, druhý má propad, a jejich výkony se vždy sečtou rovně." },
  { "Listen to L alone and R alone: each is coloured, together they are neutral.", "Poslechněte si L a R zvlášť: každý je zabarvený, dohromady jsou neutrální." },
  "Lauridsen 1954; Orban 1970" },
{ "p.spread_amount", { "Spread amount", "Množství rozprostření" }, { "Level of the Spread side signal.", "Úroveň bočního signálu Rozprostření." },
  { "Scales this generator's contribution to the side bus.", "Škáluje příspěvek tohoto generátoru do boční sběrnice." },
  { "Set it to 0 %: the module goes to sleep and costs nothing.", "Nastavte 0 %: modul usne a nic nestojí." }, "" },
{ "p.spread_source", { "Spread source", "Zdroj rozprostření" }, { "Which component Spread widens (Full engine).", "Kterou složku rozprostření rozšiřuje (plné jádro)." },
  { "Full is the whole signal; Tonal, Noise and Tonal+Noise come from the spectral split, so you can widen the room without smearing the notes.",
    "Celý je celý signál; Tónová, Šumová a Tónová+šumová pocházejí ze spektrálního rozkladu – můžete rozšířit místnost a nerozmazat tóny." },
  { "Route Spread to Noise on a vocal: breaths and room widen, the voice stays put.", "Pošlete rozprostření na Šumovou na zpěvu: dech a místnost se rozšíří, hlas zůstane." }, "" },
{ "p.spread_type", { "Spread type", "Typ rozprostření" }, { "Delay: a plain delay (Lauridsen). Cascade: a chain of all-pass sections (Orban).",
    "Zpoždění: prosté zpoždění (Lauridsen). Kaskáda: řetěz všepropustných článků (Orban)." },
  { "A delay gives evenly spaced comb teeth; a cascade spreads the phase change smoothly and sounds less coloured per channel.",
    "Zpoždění dává rovnoměrně rozložené zuby hřebene; kaskáda rozloží změnu fáze plynule a v každém kanálu zabarvuje méně." },
  { "Switch types and listen to one channel only.", "Přepínejte typy a poslouchejte jen jeden kanál." }, "Lauridsen 1954; Orban 1970" },
{ "p.spread_time_ms", { "Spread time", "Čas rozprostření" }, { "Delay of the Delay type.", "Zpoždění u typu Zpoždění." },
  { "Sets the spacing of the complementary combs (1 / time).", "Určuje rozestup doplňkových hřebenů (1 / čas)." },
  { "Short times give wide, coarse combs; long times fine, dense ones.", "Krátké časy dávají široké hrubé hřebeny, dlouhé jemné a husté." }, "Schroeder 1958" },
{ "p.spread_density", { "Spread density", "Hustota rozprostření" }, { "Number of all-pass sections in the cascade.", "Počet všepropustných článků v kaskádě." },
  { "Each section rotates the phase around its centre frequency; more sections mean more, finer alternations between left and right.",
    "Každý článek otáčí fázi kolem svého středního kmitočtu; víc článků znamená víc a jemnějších střídání mezi levou a pravou stranou." },
  { "Sweep from 2 to 24 on noise.", "Projeďte od 2 do 24 na šumu." }, "Orban 1970" },
{ "p.spread_f_lo", { "Spread low", "Dolní kmitočet rozprostření" }, { "Lowest section frequency.", "Kmitočet nejnižšího článku." },
  { "Sections are spread between low and high on a logarithmic scale.", "Články jsou rozloženy mezi dolním a horním kmitočtem v logaritmickém měřítku." },
  { "Raise it to keep the low mids untouched.", "Zvyšte jej, aby zůstaly nízké středy nedotčené." }, "" },
{ "p.spread_f_hi", { "Spread high", "Horní kmitočet rozprostření" }, { "Highest section frequency.", "Kmitočet nejvyššího článku." },
  { "Above it the phase no longer alternates, so the top end stays focused.", "Nad ním se fáze už nestřídá, takže výšky zůstanou soustředěné." },
  { "Lower it on bright sources to avoid a fizzy top.", "Na jasných zdrojích jej snižte, aby výšky nešuměly." }, "" },
{ "p.spread_skew", { "Spread skew", "Zkosení rozprostření" }, { "Bunches the sections toward the low or the high end.", "Shlukuje články k dolnímu nebo hornímu konci." },
  { "Positive skew places more sections at low frequencies (x^(2^skew) mapping).", "Kladné zkosení umístí víc článků k nízkým kmitočtům (mapování x^(2^skew))." },
  { "Combine with the band widths for a shaped spread.", "Kombinujte se šířkou pásem pro tvarované rozprostření." }, "Gerzon 1992" },
{ "p.spread_q", { "Spread Q", "Q rozprostření" }, { "Sharpness of each all-pass section.", "Ostrost každého všepropustného článku." },
  { "High Q concentrates each phase turn in a narrow band; low Q smears it.", "Vysoké Q soustředí každé otočení fáze do úzkého pásma, nízké je rozmaže." },
  { "Higher Q sounds more 'phasey'; lower Q smoother.", "Vyšší Q zní „fázověji“, nižší hladčeji." }, "" },

// ---------------------------------------------------------------- delay
{ "card.delay",
  { "Delay (Haas)", "Zpoždění (Haas)" },
  { "The precedence effect: a short delay between the channels moves and widens the image.",
    "Efekt přednosti: krátké zpoždění mezi kanály posouvá a rozšiřuje obraz." },
  { "Between about 1 and 35 ms the ear fuses the two arrivals into one sound heard from the earlier side. Mono-safe mode adds only the difference, which is a half-depth comb; mid blend restores the real dry/delayed pair.",
    "Mezi asi 1 a 35 ms ucho spojí oba příchody v jeden zvuk slyšený ze strany, která přišla dřív. Mono-kompatibilní režim přidá jen rozdíl, tedy hřeben poloviční hloubky; příměs středu obnoví skutečný pár suchý/zpožděný." },
  { "Sweep the time from 1 to 40 ms: from a shifted image to a distinct echo.", "Projeďte čas od 1 do 40 ms: od posunutého obrazu po zřetelnou ozvěnu." },
  "Haas 1951; Wallach, Newman and Rosenzweig 1949" },
{ "p.delay_amount", { "Delay amount", "Množství zpoždění" }, { "Level of the Haas side signal.", "Úroveň bočního signálu Haas." },
  { "Scales the generator's side and mid difference.", "Škáluje bok a rozdíl středu tohoto generátoru." }, { "At 0 % it sleeps.", "Při 0 % spí." }, "" },
{ "p.delay_source", { "Delay source", "Zdroj zpoždění" }, { "Which component is delayed (Full engine).", "Která složka se zpožďuje (plné jádro)." },
  { "Delaying only the Noise component widens ambience without echoing the notes.", "Zpoždění jen šumové složky rozšíří ambienci, aniž by se tóny ozývaly." },
  { "Compare Full and Noise on a vocal.", "Porovnejte Celý a Šumovou na zpěvu." }, "" },
{ "p.delay_time_ms", { "Delay time", "Čas zpoždění" }, { "Delay between the channels.", "Zpoždění mezi kanály." },
  { "Sets the comb spacing (1 / time) and where the precedence effect turns into an echo.", "Určuje rozestup hřebene (1 / čas) a hranici, kde se efekt přednosti mění v ozvěnu." },
  { "Find the longest time that still sounds like one source.", "Najděte nejdelší čas, který ještě zní jako jeden zdroj." }, "Haas 1951" },
{ "p.delay_lp_hz", { "Delay low-pass", "Dolní propust zpoždění" }, { "Darkens the delayed copy.", "Ztmaví zpožděnou kopii." },
  { "A real reflection is duller than the direct sound; low-passing the copy makes the effect more natural and the combs softer at the top.",
    "Skutečný odraz je tmavší než přímý zvuk; dolní propust na kopii dělá efekt přirozenějším a hřebeny ve výškách měkčími." },
  { "Try 6 kHz with a 20 ms delay.", "Zkuste 6 kHz se zpožděním 20 ms." }, "" },
{ "p.delay_side", { "Delay side", "Strana zpoždění" }, { "Which channel carries the delayed copy.", "Který kanál nese zpožděnou kopii." },
  { "The image moves toward the undelayed channel.", "Obraz se posune ke kanálu bez zpoždění." }, { "Switch sides and listen where the sound sits.", "Přepněte strany a poslouchejte, kde zvuk sedí." }, "" },

// ---------------------------------------------------------------- mod
{ "card.mod",
  { "Mod", "Modulace (Mod)" },
  { "Movement-based width: an anti-phase chorus or a micro-pitch doubler.",
    "Šíře z pohybu: protifázový chorus nebo mikrotransponovací zdvojení." },
  { "Chorus modulates two delays in opposite directions, like the classic Dimension units. Micro-pitch shifts the left channel up and the right down by a few cents: the slow beating between them reads as two performers.",
    "Chorus moduluje dvě zpoždění opačným směrem jako klasické jednotky Dimension. Mikrotransponování posune levý kanál o pár centů nahoru a pravý dolů: pomalé zázněje mezi nimi zní jako dva hráči." },
  { "Use Micro-pitch at 9 cents on a vocal with mid blend at 0 %, then 100 %.", "Použijte mikrotransponování 9 centů na zpěvu s příměsí středu 0 % a pak 100 %." },
  "Roland Dimension D (1979); Eventide H910 (1975)" },
{ "p.mod_amount", { "Mod amount", "Množství modulace" }, { "Level of the Mod side signal.", "Úroveň bočního signálu Modulace." },
  { "Its LFO keeps running while asleep, so it wakes in phase.", "Jeho LFO běží i ve spánku, takže se probudí ve fázi." }, { "At 0 % it sleeps.", "Při 0 % spí." }, "" },
{ "p.mod_source", { "Mod source", "Zdroj modulace" }, { "Which component is modulated (Full engine).", "Která složka se moduluje (plné jádro)." },
  { "Modulating only the Tonal part avoids chorusing noise and transients.", "Modulace jen tónové složky nemoduluje šum ani transienty." },
  { "Try Tonal on a guitar with pick noise.", "Zkuste Tónovou na kytaře s ruchy trsátka." }, "" },
{ "p.mod_type", { "Mod type", "Typ modulace" }, { "Chorus or micro-pitch.", "Chorus nebo mikrotransponování." },
  { "Chorus moves continuously; micro-pitch keeps a steady pitch offset.", "Chorus se plynule pohybuje; mikrotransponování drží stálý posun ladění." },
  { "Compare on sustained chords.", "Porovnejte na držených akordech." }, "" },
{ "p.mod_rate_hz", { "Chorus rate", "Rychlost chorusu" }, { "Speed of the chorus LFO.", "Rychlost LFO chorusu." },
  { "Slow rates sound like width, fast ones like vibrato.", "Pomalé rychlosti zní jako šíře, rychlé jako vibrato." }, { "Stay below 1 Hz for width.", "Pro šíři zůstaňte pod 1 Hz." }, "" },
{ "p.mod_depth_ms", { "Chorus depth", "Hloubka chorusu" }, { "How far the delays move.", "Jak daleko se zpoždění pohybují." },
  { "Left and right move by +depth and -depth, so their sum stays constant.", "Levý a pravý se pohybují o +hloubku a -hloubku, takže jejich součet zůstává stejný." },
  { "Deeper is wider but wobblier.", "Hlubší je širší, ale kolísavější." }, "" },
{ "p.mod_base_ms", { "Chorus base", "Základ chorusu" }, { "Centre delay of the chorus.", "Střední zpoždění chorusu." },
  { "Sets where the comb teeth sit while they sweep.", "Určuje, kde leží zuby hřebene, zatímco se pohybují." }, { "Short bases sound brighter.", "Krátký základ zní jasněji." }, "" },
{ "p.mod_cents", { "Micro-pitch cents", "Centy mikrotransponování" }, { "Pitch offset of each side.", "Posun ladění každé strany." },
  { "Left goes up, right goes down by this many cents; the beating rate grows with the offset.", "Levá jde o tolik centů nahoru, pravá dolů; rychlost záznějů roste s posunem." },
  { "5 to 12 cents is the classic doubler range.", "5 až 12 centů je klasický rozsah zdvojení." }, "" },
{ "p.mod_predelay_ms", { "Micro-pitch pre-delay", "Předzpoždění mikrotransponování" }, { "Delay before the pitch shifters.", "Zpoždění před transponováním." },
  { "Separates the copies in time as well as pitch; the right side gets 8 ms more.", "Odděluje kopie v čase i v ladění; pravá strana má o 8 ms víc." },
  { "Raise it for a looser, double-tracked feel.", "Zvyšte jej pro volnější dojem zdvojené nahrávky." }, "" },

// ---------------------------------------------------------------- velvet
{ "card.velvet",
  { "Velvet", "Velvet (sametový šum)" },
  { "A sparse decorrelator: each side is convolved with its own velvet-noise sequence.",
    "Řídký dekorelátor: každá strana prochází konvolucí se svou sekvencí sametového šumu (velvet noise)." },
  { "A velvet sequence is a few dozen signed clicks that fade over 10 to 80 ms. Convolving with two different sequences gives two channels with the same spectrum but little correlation: diffuse width, like a small room without its reverb tail.",
    "Sekvence sametového šumu je několik desítek kladných a záporných impulsů doznívajících 10 až 80 ms. Konvoluce dvěma různými sekvencemi dá dva kanály se stejným spektrem, ale malou korelací: difúzní šíři jako v malé místnosti bez dozvuku." },
  { "Watch the correlation meter fall as you raise the amount.", "Sledujte, jak korelace klesá, když zvyšujete množství." },
  "Alary, Politis and Välimäki 2017" },
{ "p.velvet_amount", { "Velvet amount", "Množství velvetu" }, { "Level of the Velvet side signal.", "Úroveň bočního signálu Velvet." },
  { "With mid blend at 100 % the outputs are fully decorrelated left and right.", "Při příměsi středu 100 % jsou výstupy vlevo a vpravo zcela dekorelované." }, { "At 0 % it sleeps.", "Při 0 % spí." }, "" },
{ "p.velvet_source", { "Velvet source", "Zdroj velvetu" }, { "Which component is decorrelated (Full engine).", "Která složka se dekoreluje (plné jádro)." },
  { "Decorrelating the Noise part gives space without blurring the notes.", "Dekorelace šumové složky dá prostor bez rozmazání tónů." }, { "Use Noise on full mixes.", "Na celých mixech použijte Šumovou." }, "" },
{ "p.velvet_size_ms", { "Velvet size", "Délka velvetu" }, { "Length of the sequences.", "Délka sekvencí." },
  { "Longer sequences decorrelate lower frequencies but start to sound like a room.", "Delší sekvence dekorelují i nižší kmitočty, ale začínají znít jako místnost." },
  { "Sweep it while playing: changes crossfade without gaps.", "Pohybujte jím za chodu: změny se prolínají bez mezer." }, "" },
{ "p.velvet_density", { "Velvet density", "Hustota velvetu" }, { "Impulses per second in the sequences.", "Počet impulsů za sekundu v sekvencích." },
  { "Higher density is smoother; lower density is sparser and cheaper.", "Vyšší hustota je hladší; nižší je řidší a levnější." }, { "1000 per second is a good start.", "Dobrý začátek je 1000 za sekundu." }, "" },
{ "p.velvet_variation", { "Velvet variation", "Varianta velvetu" }, { "Chooses one of 16 sequence pairs.", "Volí jeden z 16 párů sekvencí." },
  { "Each pair has its own fine colour; pick the one that suits the source.", "Každý pár má vlastní jemné zabarvení; vyberte, který sedí ke zdroji." }, { "Step through them on a vocal.", "Projděte je na zpěvu." }, "" },

// ---------------------------------------------------------------- pan map
{ "card.pan",
  { "Pan map", "Panoramatická mapa (Pan map)" },
  { "Adaptive spectral panning: places frequencies, partials or whole sources across the stereo field.",
    "Adaptivní spektrální panoráma: rozmisťuje kmitočty, parciály nebo celé zdroje po stereo poli." },
  { "Static mode is the classic complementary spectral split. Tracks follows each partial and keeps it in one place. Groups gathers partials that share a harmonic series and onset into sources, and gives each source its own position, keeping a melody in place.",
    "Statický režim je klasické doplňkové rozdělení spektra. Stopy sledují každý parciál a drží ho na místě. Skupiny spojují parciály se stejnou harmonickou řadou a nástupem do zdrojů a dávají každému zdroji vlastní pozici – melodie zůstane na místě." },
  { "Use the Two sources teaching source with Groups and watch the Pan map display.", "Použijte výukový zdroj Dva zdroje s režimem Skupiny a sledujte zobrazení panoramatické mapy." },
  "McAulay and Quatieri 1986; Bregman 1990" },
{ "p.pan_amount", { "Pan map amount", "Množství pan. mapy" }, { "Level of the Pan map side signal.", "Úroveň bočního signálu pan. mapy." },
  { "Works in the Full engine only.", "Funguje jen v plném jádru." }, { "Turn it up slowly: the panning is coherent with the dry, so it moves sounds rather than blurring them.", "Zvyšujte pomalu: panoráma je koherentní se suchým signálem, takže zvuky posouvá, ne rozmazává." }, "" },
{ "p.pan_mode", { "Pan mode", "Režim pan. mapy" }, { "Static, Tracks or Groups.", "Statická, Stopy nebo Skupiny." },
  { "Each mode decides the pan of a frequency bin from a different level of analysis.", "Každý režim určuje panorámu binu z jiné úrovně analýzy." }, { "Compare all three on a chord progression.", "Porovnejte všechny tři na sledu akordů." }, "" },
{ "p.pan_depth", { "Pan depth", "Hloubka pan. mapy" }, { "How far bins are panned.", "Jak daleko se biny panorámují." },
  { "100 % reaches the speakers; lower values keep everything nearer the centre.", "100 % dosáhne k reproduktorům; nižší hodnoty drží vše blíž středu." }, { "70 % is natural on most material.", "Na většině materiálu je přirozených 70 %." }, "" },
{ "p.pan_density", { "Pan density", "Hustota pan. mapy" }, { "Cycles per octave of the static pan curve.", "Počet cyklů na oktávu statické křivky panorámy." },
  { "Static and Tracks modes pan by a sine of log frequency; density sets how often it swings left and right.", "Statický režim a Stopy panorámují podle sinu logaritmu kmitočtu; hustota určuje, jak často se křivka houpe vlevo a vpravo." },
  { "Low densities give a few wide zones; high ones a fine checkerboard.", "Nízké hustoty dají pár širokých zón, vysoké jemnou šachovnici." }, "" },
{ "p.pan_bass_center_hz", { "Bass centre", "Střed basů" }, { "Frequencies below this stay in the centre.", "Kmitočty pod touto hodnotou zůstanou uprostřed." },
  { "Applies to the curve and to groups whose fundamental is lower.", "Platí pro křivku i pro skupiny s nižším základním tónem." }, { "Raise it for bass-heavy material.", "Pro materiál s výraznými basy jej zvyšte." }, "" },
{ "p.pan_max_groups", { "Max groups", "Max. skupin" }, { "How many sources Groups mode separates.", "Kolik zdrojů režim Skupiny oddělí." },
  { "Further partials join an existing source or stay centred.", "Další parciály se přidají k existujícímu zdroji nebo zůstanou uprostřed." }, { "Lower it for simpler arrangements.", "Pro jednodušší aranžmá jej snižte." }, "" },

// ---------------------------------------------------------------- coherence
{ "card.coherence",
  { "Coherence designer", "Návrhář koherence" },
  { "You choose how similar left and right are at each frequency; the plugin synthesises exactly that.",
    "Vyberete, jak podobné mají být levý a pravý kanál na každém kmitočtu; plugin přesně to syntetizuje." },
  { "With the dry mid M and a decorrelated copy D, L = M + aD and R = M - aD keep the mono sum exact while their coherence follows your curve. The gain a is solved per band from measurements, so it holds even on tonal material. The pair modes take the curve from the physics of real microphones: two spaced omnis, an XY pair, Blumlein, ORTF.",
    "Se suchým středem M a dekorelovanou kopií D zachovají L = M + aD a R = M - aD mono součet přesně, zatímco jejich koherence sleduje vaši křivku. Zisk a se počítá po pásmech z měření, takže platí i na tónovém materiálu. Režimy párů berou křivku z fyziky skutečných mikrofonů: dvě kulové od sebe, pár XY, Blumlein, ORTF." },
  { "Choose Spaced pair and sweep the spacing: you are moving two virtual microphones apart.",
    "Zvolte Rozložený pár a měňte rozestup: oddalujete dva virtuální mikrofony." },
  "Breebaart et al. 2005; Cook et al. 1955; Elko 2001" },
{ "p.coh_amount", { "Coherence amount", "Množství koherence" }, { "How far toward the target curve.", "Jak daleko k cílové křivce." },
  { "100 % reaches the target; lower amounts move every band toward fully coherent (mono).", "100 % dosáhne cíle; nižší množství posouvá každé pásmo k plné koherenci (mono)." },
  { "Watch target and achieved curves on the Coherence tab.", "Sledujte cílovou a dosaženou křivku na kartě Koherence." }, "" },
{ "p.coh_source", { "Coherence source", "Zdroj koherence" }, { "Which component is designed (Full engine).", "Která složka se navrhuje (plné jádro)." },
  { "Designing only the Noise part shapes the room while notes stay focused.", "Návrh jen šumové složky tvaruje místnost, tóny zůstanou ostré." }, { "Try Noise on a piano recording.", "Zkuste Šumovou na nahrávce klavíru." }, "" },
{ "p.coh_mode", { "Coherence mode", "Režim koherence" }, { "Draw a curve, or take it from a microphone pair.", "Nakreslete křivku nebo ji převezměte z mikrofonního páru." },
  { "Spaced pairs lose coherence with frequency (sin(x)/x); coincident pairs have the same coherence at all frequencies.", "Rozložené páry ztrácejí koherenci s kmitočtem (sin(x)/x); koincidenční páry ji mají na všech kmitočtech stejnou." },
  { "Compare Spaced and Coincident at similar settings.", "Porovnejte rozložený a koincidenční pár při podobném nastavení." }, "Elko 2001" },
{ "p.coh_p63", { "Coherence at 63 Hz", "Koherence na 63 Hz" }, { "Target coherence of the lowest curve point.", "Cílová koherence nejnižšího bodu křivky." },
  { "1 is mono, 0 is uncorrelated, negative values are wider than the speakers.", "1 je mono, 0 nekorelované, záporné hodnoty jsou širší než reproduktory." }, { "Keep lows near 1 for a solid mix.", "Pro pevný mix držte basy blízko 1." }, "" },
{ "p.coh_p250", { "Coherence at 250 Hz", "Koherence na 250 Hz" }, { "Target coherence at 250 Hz.", "Cílová koherence na 250 Hz." },
  { "The curve passes through the five points smoothly.", "Křivka prochází pěti body plynule." }, { "Lower it to warm up the low mids' width.", "Snižte ji pro širší nízké středy." }, "" },
{ "p.coh_p1k", { "Coherence at 1 kHz", "Koherence na 1 kHz" }, { "Target coherence at 1 kHz.", "Cílová koherence na 1 kHz." },
  { "Around 1 kHz the ear judges width from both time and level cues.", "Kolem 1 kHz ucho posuzuje šíři podle časových i úrovňových rozdílů." }, { "0.3 is open but stable.", "0,3 je otevřené, ale stabilní." }, "" },
{ "p.coh_p4k", { "Coherence at 4 kHz", "Koherence na 4 kHz" }, { "Target coherence at 4 kHz.", "Cílová koherence na 4 kHz." },
  { "Upper mids decide presence; lower values add air.", "Horní středy určují prezenci; nižší hodnoty přidají vzduch." }, { "Try 0 here.", "Zkuste zde 0." }, "" },
{ "p.coh_p16k", { "Coherence at 16 kHz", "Koherence na 16 kHz" }, { "Target coherence at the top.", "Cílová koherence nahoře." },
  { "Real rooms are almost incoherent this high.", "Skutečné místnosti jsou takhle vysoko téměř nekoherentní." }, { "0 sounds natural.", "0 zní přirozeně." }, "" },
{ "p.coh_spacing_cm", { "Mic spacing", "Rozestup mikrofonů" }, { "Distance between the two virtual microphones.", "Vzdálenost mezi dvěma virtuálními mikrofony." },
  { "Coherence of a spaced pair falls to zero at f = c / (2 d): wider spacing decorrelates lower frequencies.", "Koherence rozloženého páru klesne na nulu při f = c / (2 d): větší rozestup dekoreluje nižší kmitočty." },
  { "40 cm is a common AB pair; 1 m and more sounds like a big hall.", "40 cm je běžný pár AB; 1 m a více zní jako velký sál." }, "Cook et al. 1955" },
{ "p.coh_angle_deg", { "Mic angle", "Úhel mikrofonů" }, { "Angle between the microphone axes.", "Úhel mezi osami mikrofonů." },
  { "Wider angles make directional pairs less coherent.", "Větší úhly snižují koherenci směrových párů." }, { "90 degrees is XY, 110 ORTF.", "90 stupňů je XY, 110 ORTF." }, "" },
{ "p.coh_pattern", { "Mic pattern", "Charakteristika mikrofonů" }, { "Polar pattern of the virtual microphones.", "Směrová charakteristika virtuálních mikrofonů." },
  { "Omnis are fully coherent when coincident; figure-8s at 90 degrees are fully decorrelated (Blumlein).", "Kulové jsou v koincidenci plně koherentní; osmičky pod úhlem 90 stupňů jsou plně dekorelované (Blumlein)." },
  { "Compare Cardioid and Figure-8 at 90 degrees.", "Porovnejte ledvinu a osmičku při 90 stupních." }, "Blumlein 1931; Elko 2001" },
{ "p.coh_transient", { "Transient protection", "Ochrana transientů" }, { "Keeps attacks coherent so they stay centred and sharp.", "Udrží náběhy koherentní, takže zůstanou uprostřed a ostré." },
  { "Bins the analysis marks as transient get less decorrelation.", "Biny, které analýza označí jako transientní, dostanou méně dekorelace." }, { "Use 70 % or more on drums.", "Na bicí použijte 70 % a víc." }, "" },

// ---------------------------------------------------------------- double
{ "card.double",
  { "Double-tracker", "Zdvojení stopy (ADT)" },
  { "Two synthetic takes whose timing, pitch, level and tone drift like two human performances.",
    "Dva syntetické záznamy, jejichž načasování, ladění, úroveň a barva kolísají jako dva lidské výkony." },
  { "Artificial double tracking began at Abbey Road in 1966 with a tape delay varied by hand. Here each take reads the input at a slowly wandering delay with a little random pitch wobble. Unlike a chorus there is no repeating cycle, so it never sounds mechanical.",
    "Umělé zdvojení vzniklo v Abbey Road roku 1966 s páskovým zpožděním měněným ručně. Zde každý záznam čte vstup s pomalu se toulajícím zpožděním a trochou náhodného kolísání ladění. Na rozdíl od chorusu se nic neopakuje, takže nikdy nezní mechanicky." },
  { "Set mid blend to 100 %: left and right become two 'performances' with no dry.", "Nastavte příměs středu na 100 %: levý a pravý budou dva „výkony“ bez suchého signálu." },
  "Townsend 1966 (ADT)" },
{ "p.dbl_amount", { "Double amount", "Množství zdvojení" }, { "Level of the double-tracker side signal.", "Úroveň bočního signálu zdvojení." },
  { "Its drift keeps running while asleep.", "Jeho kolísání běží i ve spánku." }, { "At 0 % it sleeps.", "Při 0 % spí." }, "" },
{ "p.dbl_source", { "Double source", "Zdroj zdvojení" }, { "Which component is doubled (Full engine).", "Která složka se zdvojuje (plné jádro)." },
  { "Doubling only the Tonal part keeps consonants and breaths single.", "Zdvojení jen tónové složky ponechá souhlásky a nádechy jednoduché." }, { "Try Tonal on vocals.", "Zkuste Tónovou na zpěvu." }, "" },
{ "p.dbl_offset_ms", { "Double offset", "Posun zdvojení" }, { "Average delay of the takes.", "Průměrné zpoždění záznamů." },
  { "10 to 30 ms sounds like a second take; less like a thickened single one.", "10 až 30 ms zní jako druhý záznam; méně jako zahuštěný jediný." }, { "Start at 18 ms.", "Začněte na 18 ms." }, "" },
{ "p.dbl_drift_ms", { "Double drift", "Kolísání zdvojení" }, { "How far each take's timing wanders.", "Jak daleko se načasování každého záznamu toulá." },
  { "Independent random drift on each side, like players never quite together.", "Nezávislé náhodné kolísání na každé straně, jako hráči, kteří nejsou nikdy přesně spolu." }, { "3 ms is natural; 8 ms loose.", "3 ms je přirozené, 8 ms volné." }, "" },
{ "p.dbl_drift_rate", { "Drift rate", "Rychlost kolísání" }, { "How quickly the drift changes.", "Jak rychle se kolísání mění." },
  { "Slow drift sounds human; fast drift starts to sound like wow and flutter.", "Pomalé kolísání zní lidsky, rychlé začíná znít jako kolísání pásku." }, { "Keep it below 0.5 Hz.", "Držte pod 0,5 Hz." }, "" },
{ "p.dbl_pitch_cents", { "Pitch drift", "Kolísání ladění" }, { "Random pitch wobble of the takes, in cents.", "Náhodné kolísání ladění záznamů v centech." },
  { "Produced by modulating the delay, as on tape.", "Vzniká modulací zpoždění, jako na pásku." }, { "4 cents is subtle; 10 wide.", "4 centy jsou jemné, 10 široké." }, "" },
{ "p.dbl_level_db", { "Level drift", "Kolísání úrovně" }, { "Random level variation of the takes.", "Náhodné kolísání úrovně záznamů." },
  { "Real takes differ slightly in loudness from moment to moment.", "Skutečné záznamy se v hlasitosti chvíli od chvíle mírně liší." }, { "Keep it under 1 dB.", "Držte pod 1 dB." }, "" },
{ "p.dbl_tone_db", { "Tone difference", "Rozdíl barvy" }, { "One take brighter, the other darker.", "Jeden záznam jasnější, druhý tmavší." },
  { "A high shelf of +tone/2 on the left and -tone/2 on the right.", "Výšková polička +barva/2 vlevo a -barva/2 vpravo." }, { "A small negative value sounds like a second microphone.", "Malá záporná hodnota zní jako druhý mikrofon." }, "" },
{ "p.dbl_seed", { "Double seed", "Seed zdvojení" }, { "Chooses one of 16 independent drift patterns.", "Volí jeden z 16 nezávislých vzorů kolísání." },
  { "The same seed always gives the same performance.", "Stejný seed dá vždy stejný výkon." }, { "Try a few for the one that grooves.", "Vyzkoušejte několik a najděte ten, který sedí." }, "" },

// ---------------------------------------------------------------- room
{ "card.room",
  { "Room cues", "Prostorové odrazy" },
  { "The first reflections of a small virtual room, heard by a virtual ORTF pair: width and depth without a reverb tail.",
    "První odrazy malé virtuální místnosti zachycené virtuálním párem ORTF: šíře a hloubka bez dozvuku." },
  { "Our sense of width comes largely from early lateral reflections. An image-source model computes up to 24 reflections within 80 ms; each reaches the two microphones at its own time and level, which decorrelates them. Mono-safe mode keeps only their difference.",
    "Pocit šíře vychází hlavně z časných bočních odrazů. Model zrcadlových zdrojů spočítá až 24 odrazů do 80 ms; každý dorazí k oběma mikrofonům v jiném čase a s jinou úrovní, a tím se dekorelují. Mono-kompatibilní režim ponechá jen jejich rozdíl." },
  { "Sweep the room size from 2 to 30 m.", "Projeďte velikost místnosti od 2 do 30 m." },
  "Barron and Marshall 1981; Allen and Berkley 1979" },
{ "p.room_amount", { "Room amount", "Množství prostoru" }, { "Level of the room-cue side signal.", "Úroveň bočního signálu prostorových odrazů." },
  { "With mid blend the full reflections are heard, not only their difference.", "S příměsí středu zazní celé odrazy, ne jen jejich rozdíl." }, { "At 0 % it sleeps.", "Při 0 % spí." }, "" },
{ "p.room_source", { "Room source", "Zdroj prostoru" }, { "Which component feeds the room (Full engine).", "Která složka napájí místnost (plné jádro)." },
  { "Feeding only Tonal avoids reflecting transients.", "Napájení jen tónovou složkou neodráží transienty." }, { "Try Tonal on drums.", "Zkuste Tónovou na bicích." }, "" },
{ "p.room_size", { "Room size", "Velikost místnosti" }, { "Width of the room; depth is 0.8 of it.", "Šířka místnosti; hloubka je 0,8 z ní." },
  { "Larger rooms delay the reflections more and spread them further.", "Větší místnosti odrazy víc zpozdí a víc rozprostřou." }, { "6 m is a studio, 20 m a hall.", "6 m je studio, 20 m sál." }, "Allen and Berkley 1979" },
{ "p.room_distance", { "Source distance", "Vzdálenost zdroje" }, { "Distance from the source to the microphones.", "Vzdálenost od zdroje k mikrofonům." },
  { "Farther sources hear relatively stronger, earlier reflections.", "Vzdálenější zdroje mají relativně silnější a dřívější odrazy." }, { "Move it out to push the sound back.", "Zvětšete ji a zvuk se posune dozadu." }, "" },
{ "p.room_absorb", { "Absorption", "Pohltivost" }, { "How much energy each wall absorbs.", "Kolik energie každá stěna pohltí." },
  { "Each wall hit multiplies a reflection by sqrt(1 - absorption).", "Každý dopad na stěnu násobí odraz hodnotou sqrt(1 - pohltivost)." }, { "Higher absorption is drier.", "Vyšší pohltivost je sušší." }, "" },
{ "p.room_order", { "Reflection order", "Řád odrazů" }, { "1: six first reflections. 2: also the 18 second-order ones.", "1: šest prvních odrazů. 2: i 18 odrazů druhého řádu." },
  { "Second order fills the space between the first reflections.", "Druhý řád vyplní prostor mezi prvními odrazy." }, { "Compare 1 and 2 on a vocal.", "Porovnejte 1 a 2 na zpěvu." }, "" },
{ "p.room_damp_hz", { "Damping", "Tlumení výšek" }, { "High-frequency loss of the reflections.", "Ztráta výšek v odrazech." },
  { "Each wall hit darkens a reflection further.", "Každý dopad na stěnu odraz dál ztmaví." }, { "Lower values sound softer and farther.", "Nižší hodnoty zní měkčeji a vzdáleněji." }, "" },

// ---------------------------------------------------------------- image
{ "card.image",
  { "Image expander", "Rozšíření stereobáze" },
  { "For stereo input: moves each panned source outward from where it already is, stopping at the speaker.",
    "Pro stereo vstup: posouvá každý panorámovaný zdroj ven z místa, kde už je, a zastaví ho u reproduktoru." },
  { "Unlike a width knob it works per frequency: panned sources move outward with a soft limit at the speaker, so nothing goes out of phase, while diffuse sound (room, reverb) is scaled separately and the bass below the keep-below frequency is left alone.",
    "Na rozdíl od knoflíku šíře pracuje po kmitočtech: panorámované zdroje se posouvají ven s měkkým omezením u reproduktoru, takže nic nejde do protifáze, zatímco difúzní zvuk (místnost, dozvuk) se škáluje zvlášť a basy pod nastaveným kmitočtem zůstanou." },
  { "Feed a stereo mix and compare expansion 150 % with Width at 150 % on Spread.", "Pusťte stereo mix a porovnejte rozšíření 150 % se šíří 150 % na rozprostření." },
  "Avendano 2003; Avendano and Jot 2004" },
{ "p.img_amount", { "Image expansion", "Rozšíření obrazu" }, { "How far panned sources move outward.", "Jak daleko se panorámované zdroje posunou ven." },
  { "100 % leaves positions unchanged.", "100 % ponechá pozice beze změny." }, { "150 % is a strong but clean widening.", "150 % je silné, ale čisté rozšíření." }, "" },
{ "p.img_diffuse", { "Diffuse level", "Úroveň difúzní složky" }, { "Scales the diffuse (unpanned, decorrelated) part of the side.", "Škáluje difúzní (nepanorámovanou, dekorelovanou) část strany." },
  { "Lets you widen sources without widening the room, or the other way round.", "Umožní rozšířit zdroje bez rozšíření místnosti, nebo naopak." }, { "Lower it on a reverberant mix.", "Na mixu s dozvukem ji snižte." }, "" },
{ "p.img_center_hz", { "Keep below", "Ponechat pod" }, { "Bins below this frequency are left unchanged.", "Biny pod tímto kmitočtem zůstanou beze změny." },
  { "Keeps the bass image as it was mixed.", "Zachová obraz basů tak, jak byl namixován." }, { "120 Hz suits most mixes.", "Většině mixů vyhovuje 120 Hz." }, "" },

// ---------------------------------------------------------------- displays
{ "disp.goniometer",
  { "Goniometer", "Goniometr" },
  { "Plots each sample pair: mid upward, side sideways.", "Vykresluje každý pár vzorků: střed nahoru, strana do stran." },
  { "A vertical line is mono, a horizontal line is pure side (out of phase), a round cloud is uncorrelated stereo. A shape leaning toward L or R is panned.",
    "Svislá čára je mono, vodorovná je čistá strana (protifáze), kulatý mrak je nekorelované stereo. Tvar nakloněný k L nebo R je panorámovaný." },
  { "Raise Velvet and watch the line open into a cloud.", "Zvyšte Velvet a sledujte, jak se čára otevře v mrak." }, "" },
{ "disp.material",
  { "Material", "Materiál" },
  { "What Easy mode hears: percussive, tonal or mixed, as three weights.", "Co snadný režim slyší: perkusivní, tónový nebo smíšený materiál, jako tři váhy." },
  { "A short spectrum counts hits (onsets where most frequencies rise together) and measures how much energy sits in steady spectral peaks. The weights follow slowly (about 2 s), and the mapping blends one set of curves per class: percussive material keeps its hits centred, tonal material uses more movement and placement.",
    "Krátké spektrum počítá údery (nástupy, při nichž stoupá většina kmitočtů zároveň) a měří, kolik energie leží ve stálých spektrálních vrcholech. Váhy se mění pomalu (asi 2 s) a mapování míchá jednu sadu křivek na každou třídu: perkusivní materiál drží údery uprostřed, tónový víc využívá pohyb a rozmístění." },
  { "Switch the teaching source between the drum loop and the melody and watch the weights move.",
    "Přepínejte výukový zdroj mezi bicí smyčkou a melodií a sledujte, jak se váhy mění." }, "" },
{ "disp.correlation",
  { "Correlation meter", "Korelační měřič (korelátor)" },
  { "+1 is mono, 0 uncorrelated, negative values mean the channels partly cancel.",
    "+1 je mono, 0 nekorelované, záporné hodnoty znamenají, že se kanály částečně ruší." },
  { "Measured over 100 ms. Staying above 0 keeps the mix stable on speakers and in mono; the guard enforces it.",
    "Měří se za 100 ms. Držet se nad 0 udrží mix stabilní na reproduktorech i v mono; hlídač to zajistí." },
  { "Turn the guard off at Width 200 % and watch it dip red.", "Vypněte hlídač při šíři 200 % a sledujte, jak se propadne do červené." }, "IEC 60268-18" },
{ "disp.levels", { "Level meters", "Měřiče úrovně" }, { "Peak level of each output channel, with a 1.5 s hold.", "Špičková úroveň každého výstupního kanálu s držením 1,5 s." },
  { "The part above 0 dBFS turns red.", "Část nad 0 dBFS zčervená." }, { "Keep peaks below 0 dB.", "Držte špičky pod 0 dB." }, "" },
{ "disp.asw",
  { "Perceived width", "Vnímaná šíře" },
  { "An estimate of how wide a listener hears the sound: 0 is a point, 1 fully diffuse.",
    "Odhad, jak široce posluchač zvuk slyší: 0 je bod, 1 zcela difúzní." },
  { "A virtual listener with a spherical head sits in a standard ±30° speaker triangle (or wears headphones). The meter is 1 minus the interaural cross-correlation in the 500 Hz to 2 kHz octaves (IACC_E3). On speakers, crosstalk between the ears limits how wide anything can sound, which is why decorrelation beyond a point stops helping.",
    "Virtuální posluchač s kulovou hlavou sedí ve standardním trojúhelníku reproduktorů ±30° (nebo má sluchátka). Měřič ukazuje 1 minus mezioušní vzájemnou korelaci v oktávách 500 Hz až 2 kHz (IACC_E3). Na reproduktorech přeslech mezi ušima omezuje, jak široce cokoli může znít – proto dekorelace od určité míry už nepomáhá." },
  { "Switch Speakers and Headphones on a wide preset.", "Přepínejte Reproduktory a Sluchátka na širokém presetu." },
  "Brown and Duda 1998; Hidaka, Beranek and Okano 1995" },
{ "disp.pan",
  { "Pan map display", "Zobrazení pan. mapy" },
  { "Where each frequency is panned (left on top, right at the bottom), brightness by level.",
    "Kam je který kmitočet panorámován (vlevo nahoře, vpravo dole), jas podle úrovně." },
  { "Shows the Pan map's current pan field in 128 points from 40 Hz to 16 kHz.", "Ukazuje aktuální pole panorámy pan. mapy ve 128 bodech od 40 Hz do 16 kHz." },
  { "Play a melody with Groups: its notes stay on one line.", "Pusťte melodii s režimem Skupiny: její tóny zůstanou na jedné čáře." }, "" },
{ "disp.coherence",
  { "Coherence view", "Zobrazení koherence" },
  { "Target coherence (accent) and the coherence actually achieved, per band.", "Cílová koherence (zvýrazněná) a skutečně dosažená, po pásmech." },
  { "Drag the five points in Curve mode. In the pair modes the microphones are drawn to scale.", "V režimu Křivka táhněte pěti body. V režimech párů jsou mikrofony nakresleny v měřítku." },
  { "Compare the curve with the correlation meter.", "Porovnejte křivku s korelačním měřičem." }, "" },
{ "disp.bands",
  { "Bands view", "Zobrazení pásem" },
  { "Correlation and mono-fold deviation in 24 third-octave bands.", "Korelace a odchylka mono součtu ve 24 třetinooktávových pásmech." },
  { "Mono fold is the level of (L + R) / 2 against the dry mid: exactly 0 dB whenever the plugin is mono-safe.", "Odchylka mono součtu je úroveň (L + R) / 2 proti suchému středu: přesně 0 dB vždy, když je plugin mono-kompatibilní." },
  { "Raise mid blend on the Haas preset and watch the comb appear.", "Zvyšte příměs středu na presetu Haas a sledujte, jak se objeví hřeben." }, "" },
{ "disp.flow",
  { "Signal flow", "Tok signálu" },
  { "The whole plugin as a diagram, with each signal's live waveform.", "Celý plugin jako schéma s živým průběhem každého signálu." },
  { "Generators run in parallel and add only to the side; the dry mid passes through untouched. Edge thickness follows level; sleeping modules are dimmed. Click a node to open its waveform in Scopes.",
    "Generátory běží souběžně a přidávají jen do strany; suchý střed prochází nedotčen. Tloušťka spojů odpovídá úrovni; spící moduly jsou ztlumené. Klepnutím na uzel otevřete jeho průběh v Průbězích." },
  { "Mute the input and watch modules fall asleep one by one.", "Ztlumte vstup a sledujte, jak moduly jeden po druhém usínají." }, "" },
{ "disp.scopes",
  { "Scopes", "Průběhy" },
  { "Waveforms of any signal path, stacked on one time axis.", "Průběhy libovolných signálových cest na jedné časové ose." },
  { "Every lane is aligned to the output, so cause and effect line up vertically. The Activity lane shows which modules are awake.", "Všechny stopy jsou zarovnány k výstupu, takže příčina a následek leží pod sebou. Stopa Aktivita ukazuje, které moduly běží." },
  { "Put the duck and the side in two lanes and play drums.", "Dejte útlum a stranu do dvou stop a pusťte bicí." }, "" },
{ "ui.learn", { "Learn", "Učení" }, { "Eleven lessons about stereo width: how we hear it, how it is made, and how to use it in a mix.", "Jedenáct lekcí o stereo šíři: jak ji slyšíme, jak se vytváří a jak ji použít v mixu." },
  { "Each lesson explains one idea step by step and highlights the controls involved. Where a step can be heard, Apply sets up a demonstration as one undoable step. Long texts in the info panel scroll with the mouse wheel; the entry stays while the mouse is over the panel.", "Každá lekce krok za krokem vysvětlí jednu myšlenku a zvýrazní ovládací prvky, kterých se týká. Kde lze krok slyšet, Použít připraví ukázku jako jeden krok, který lze vrátit. Dlouhé texty v informačním panelu se posouvají kolečkem myši; dokud je myš nad panelem, obsah se nemění." },
  { "Start with How we hear width, then Mid and side.", "Začněte lekcí Jak slyšíme šíři a pak Střed a strana." }, "" },
{ "ui.language", { "Language", "Jazyk" }, { "Switches the interface between English and Czech.", "Přepíná rozhraní mezi angličtinou a češtinou." },
  { "The choice is remembered for new instances and saved with the session. Host automation names stay English.", "Volba se pamatuje pro nové instance a ukládá se s projektem. Názvy automatizace v hostiteli zůstávají anglicky." },
  { "", "" }, "" },
{ "ui.undo", { "Undo", "Zpět" }, { "Steps back through your changes.", "Vrací se o krok ve vašich změnách." },
  { "Each knob gesture and each preset load is one step; undo restores values exactly.", "Každý pohyb knoflíkem a každé načtení presetu je jeden krok; zpět obnoví hodnoty přesně." }, { "Cmd-Z also works.", "Funguje i Cmd-Z." }, "" },
{ "ui.redo", { "Redo", "Znovu" }, { "Re-applies an undone change.", "Znovu uplatní vrácenou změnu." }, { "", "" }, { "Shift-Cmd-Z also works.", "Funguje i Shift-Cmd-Z." }, "" },
{ "ui.ab", { "A / B compare", "Porovnání A / B" }, { "Two complete settings to compare by ear.", "Dvě úplná nastavení k porovnání sluchem." },
  { "Edit in A, copy to B, change B, then flip between them. Use Constant loudness so the louder one does not win by default.", "Upravte A, zkopírujte do B, změňte B a přepínejte. Použijte Stálou hlasitost, aby hlasitější nevyhrálo automaticky." },
  { "", "" }, "" },
{ "ui.easy", { "Easy mode", "Snadný režim" },
  { "Four macros drive the whole plugin: Width, and Character, Space and Focus to shape it.",
    "Celý plugin ovládají čtyři makra: Šíře a k jejímu dotvarování Charakter, Prostor a Fokus." },
  { "Each macro moves many internal settings along curves that were optimised by measurement over test material, within limits on mono compatibility, correlation, loudness and bass. Under the hood shows what they are doing right now; Full controls opens all of it, sounding exactly the same.",
    "Každé makro posouvá mnoho vnitřních nastavení po křivkách, které byly optimalizovány měřením na zkušebním materiálu, v mezích mono kompatibility, korelace, hlasitosti a basů. Pod kapotou ukazuje, co právě dělají; Všechny prvky otevřou celý plugin a zní přesně stejně." },
  { "Turn Width slowly from 0 to 100 % and watch the perceived-width meter rise evenly.",
    "Otáčejte pomalu Šíří od 0 do 100 % a sledujte, jak měřič vnímané šíře rovnoměrně stoupá." },
  "" },
{ "ui.expand", { "Full controls", "Všechny prvky" },
  { "Opens the complete interface with the settings Easy mode is using now.",
    "Otevře úplné rozhraní s nastaveními, která snadný režim právě používá." },
  { "Every internal parameter takes exactly the value the macros were giving it, so nothing changes in the sound. From there you can change anything. One undo step goes back.",
    "Každý vnitřní parametr dostane přesně hodnotu, kterou mu dávala makra, takže se zvuk nezmění. Pak můžete změnit cokoli. Jeden krok zpět vás vrátí." },
  { "", "" }, "" },
{ "ui.collapse", { "Easy mode", "Snadný režim" },
  { "Returns to the four macros, after asking.", "Vrátí se ke čtyřem makrům, po potvrzení." },
  { "Easy mode replaces your hand-made settings with its mapping, so it asks first; undo brings them back.",
    "Snadný režim nahradí vaše ruční nastavení svým mapováním, proto se nejprve zeptá; krok zpět je vrátí." },
  { "", "" }, "" },
{ "ui.presets", { "Presets", "Presety" }, { "Factory presets, and your own saved settings.", "Tovární presety a vaše uložená nastavení." },
  { "User presets are files in ~/Library/Audio/Presets/highda/stereophield.", "Uživatelské presety jsou soubory v ~/Library/Audio/Presets/highda/stereophield." }, { "", "" }, "" },
};


const Entry presetEntries[] = {
{ "preset.1", { "Default: Orban comb", "Výchozí: Orbanův hřeben" }, { "Eight all-pass sections widen the side at 60 %; mono stays exact. A safe, neutral starting point for anything.", "Osm všepropustných článků rozšiřuje stranu na 60 %; mono zůstává přesné. Bezpečný neutrální začátek pro cokoli." }, { "", "" }, { "", "" }, "" },
{ "preset.2", { "Classic: Haas", "Klasika: Haas" }, { "The authentic precedence effect: left dry, right delayed 15 ms. Very wide, but it combs in mono, so check with Listen: Mono.", "Původní efekt přednosti: vlevo suchý, vpravo zpožděný o 15 ms. Velmi široké, ale v mono vytváří hřeben – ověřte Poslechem Mono." }, { "", "" }, { "", "" }, "" },
{ "preset.3", { "Classic: Haas, mono-safe", "Klasika: Haas, mono-kompatibilní" }, { "The Haas delay added to the side only. Half the depth of the authentic version and no change in mono.", "Haasovo zpoždění přidané jen do strany. Poloviční hloubka původní verze a žádná změna v mono." }, { "", "" }, { "", "" }, "" },
{ "preset.4", { "Classic: Lauridsen", "Klasika: Lauridsen" }, { "A 10 ms delay as the side signal gives complementary combs, the 1954 pseudo-stereo method. Clear width with a slightly hollow colour per channel.", "Zpoždění 10 ms jako boční signál dá doplňkové hřebeny – metoda pseudostereo z roku 1954. Zřetelná šíře s mírně dutou barvou v každém kanálu." }, { "", "" }, { "", "" }, "" },
{ "preset.5", { "Classic: Orban, full depth", "Klasika: Orban, plná hloubka" }, { "The all-pass cascade at full depth. Wider than the default, still exactly mono-safe.", "Všepropustná kaskáda v plné hloubce. Širší než výchozí, stále přesně mono-kompatibilní." }, { "", "" }, { "", "" }, "" },
{ "preset.6", { "Classic: Shaped spread", "Klasika: Tvarované rozprostření" }, { "A denser cascade with narrow lows and wide highs, after Gerzon. Keeps the low end solid while the top opens up.", "Hustší kaskáda s úzkými basy a širokými výškami podle Gerzona. Basy zůstanou pevné a výšky se otevřou." }, { "", "" }, { "", "" }, "" },
{ "preset.7", { "Classic: Spectral split", "Klasika: Spektrální rozdělení" }, { "Alternating frequency zones go left and right (Full engine). The classic complementary split, half an octave per zone.", "Střídající se kmitočtová pásma jdou vlevo a vpravo (plné jádro). Klasické doplňkové rozdělení, půl oktávy na pásmo." }, { "", "" }, { "", "" }, "" },
{ "preset.8", { "Dimension chorus", "Dimension chorus" }, { "An anti-phase chorus in the style of the Roland Dimension, with its mid component. Lush and moving; not mono-safe.", "Protifázový chorus ve stylu Roland Dimension včetně složky středu. Bohatý a pohyblivý; není mono-kompatibilní." }, { "", "" }, { "", "" }, "" },
{ "preset.9", { "Dimension chorus, mono-safe", "Dimension chorus, mono-kompatibilní" }, { "The same chorus, side only. The movement is heard in stereo and disappears in mono.", "Stejný chorus, jen ve straně. Pohyb je slyšet ve stereu a v mono zmizí." }, { "", "" }, { "", "" }, "" },
{ "preset.10", { "Micro-pitch doubler", "Mikrotransponovací zdvojení" }, { "Left up and right down by 9 cents, with the mid component: the classic doubler. Thick and wide.", "Vlevo o 9 centů nahoru, vpravo dolů, včetně středu: klasické zdvojení. Husté a široké." }, { "", "" }, { "", "" }, "" },
{ "preset.11", { "Micro-pitch, mono-safe", "Mikrotransponování, mono-kompatibilní" }, { "The doubler's difference only. Width in stereo, the untouched source in mono.", "Jen rozdíl zdvojení. Šíře ve stereu, nedotčený zdroj v mono." }, { "", "" }, { "", "" }, "" },
{ "preset.12", { "Velvet diffuse", "Velvet difúzní" }, { "Velvet-noise decorrelation added to the side. Smooth, roomy width without a tail.", "Dekorelace sametovým šumem (velvet noise) přidaná do strany. Hladká prostorová šíře bez dozvuku." }, { "", "" }, { "", "" }, "" },
{ "preset.13", { "Velvet, true decorrelation", "Velvet, skutečná dekorelace" }, { "Left and right are two different velvet convolutions of the source. Maximally wide and diffuse; check mono.", "Levý a pravý jsou dvě různé konvoluce zdroje se sametovým šumem. Maximálně široké a difúzní; ověřte mono." }, { "", "" }, { "", "" }, "" },
{ "preset.14", { "Scene: Adaptive", "Scéna: Adaptivní" }, { "Sources are placed by the Pan map while the noise component is decorrelated. Wide but focused on full mixes.", "Zdroje rozmisťuje pan. mapa, zatímco šumová složka se dekoreluje. Široké, ale soustředěné na celých mixech." }, { "", "" }, { "", "" }, "" },
{ "preset.15", { "Scene: Vocal", "Scéna: Zpěv" }, { "Micro-pitch on the tonal part, velvet on the noise part, strong transient ducking. Wide doubles with crisp consonants.", "Mikrotransponování na tónové složce, velvet na šumové, silný útlum transientů. Široké zdvojení s ostrými souhláskami." }, { "", "" }, { "", "" }, "" },
{ "preset.16", { "Scene: Ensemble", "Scéna: Soubor" }, { "Up to eight sources placed by grouping, with spread and velvet on the noise. For dense arrangements.", "Až osm zdrojů rozmístěných seskupováním, s rozprostřením a velvetem na šumu. Pro hustá aranžmá." }, { "", "" }, { "", "" }, "" },
{ "preset.17", { "Scene: Stable partials", "Scéna: Stabilní parciály" }, { "Each partial keeps its own fixed position. Shimmering, stable width for sustained sounds.", "Každý parciál má svou pevnou pozici. Třpytivá, stabilní šíře pro držené zvuky." }, { "", "" }, { "", "" }, "" },
{ "preset.18", { "Virtual pair: AB omnis 40 cm", "Virtuální pár: AB kulové 40 cm" }, { "Two omnidirectional microphones 40 cm apart, as coherence. Natural, spacious and fully mono-safe.", "Dva kulové mikrofony 40 cm od sebe, jako koherence. Přirozené, prostorné a plně mono-kompatibilní." }, { "", "" }, { "", "" }, "" },
{ "preset.19", { "Virtual pair: XY cardioids", "Virtuální pár: XY ledviny" }, { "Two coincident cardioids at 90 degrees: coherence 0.75 everywhere. Focused, compatible stereo.", "Dvě koincidenční ledviny pod 90 stupni: koherence 0,75 všude. Soustředěné, kompatibilní stereo." }, { "", "" }, { "", "" }, "" },
{ "preset.20", { "Virtual pair: Blumlein", "Virtuální pár: Blumlein" }, { "Crossed figure-8s at 90 degrees, fully decorrelated diffuse sound. Very open and enveloping.", "Zkřížené osmičky pod 90 stupni, plně dekorelovaný difúzní zvuk. Velmi otevřené a obklopující." }, { "", "" }, { "", "" }, "" },
{ "preset.21", { "Virtual pair: ORTF", "Virtuální pár: ORTF" }, { "Cardioids 17 cm apart at 110 degrees, the French broadcast standard. A balanced middle ground.", "Ledviny 17 cm od sebe pod 110 stupni, francouzský rozhlasový standard. Vyvážená střední cesta." }, { "", "" }, { "", "" }, "" },
{ "preset.22", { "Coherence: tight lows, open highs", "Koherence: pevné basy, otevřené výšky" }, { "A drawn curve from fully coherent bass to slightly negative coherence at the top. Big air without a loose low end.", "Nakreslená křivka od plně koherentních basů po mírně zápornou koherenci nahoře. Hodně vzduchu bez volných basů." }, { "", "" }, { "", "" }, "" },
{ "preset.23", { "Double track: vocal", "Zdvojení: zpěv" }, { "A second synthetic take 18 ms later with gentle drift. Width that sounds like a performance.", "Druhý syntetický záznam o 18 ms později s jemným kolísáním. Šíře, která zní jako výkon." }, { "", "" }, { "", "" }, "" },
{ "preset.24", { "Double track: guitar wall", "Zdvojení: kytarová stěna" }, { "Two takes left and right with more pitch drift and no dry. The hard-panned rhythm-guitar sound.", "Dva záznamy vlevo a vpravo s větším kolísáním ladění a bez suchého signálu. Zvuk rytmických kytar natvrdo v krajích." }, { "", "" }, { "", "" }, "" },
{ "preset.25", { "Room cues: small studio", "Prostor: malé studio" }, { "First reflections of a 6 m room. Depth and a little width with no reverb tail.", "První odrazy místnosti 6 m. Hloubka a trocha šíře bez dozvuku." }, { "", "" }, { "", "" }, "" },
{ "preset.26", { "Room cues: wide hall edge", "Prostor: okraj sálu" }, { "Second-order reflections of a 20 m room, source 4 m away. Spacious, still without a tail.", "Odrazy druhého řádu v místnosti 20 m, zdroj 4 m daleko. Prostorné, stále bez dozvuku." }, { "", "" }, { "", "" }, "" },
{ "preset.27", { "Image expander: 150 %", "Rozšíření stereobáze: 150 %" }, { "For stereo mixes: every panned source moves outward by half again, stopping at the speakers. The room is widened only as much as the sources.", "Pro stereo mixy: každý panorámovaný zdroj se posune o polovinu dál ven a zastaví se u reproduktorů. Místnost se rozšíří jen tolik jako zdroje." }, { "", "" }, { "", "" }, "" },
{ "preset.28", { "Scene: Natural ensemble", "Scéna: Přirozený soubor" }, { "Sources placed by grouping, a spaced-pair coherence and a little room. Like moving a mono recording into a hall.", "Zdroje rozmístěné seskupováním, koherence rozloženého páru a trochu prostoru. Jako přenést mono nahrávku do sálu." }, { "", "" }, { "", "" }, "" },
{ "preset.29", { "Scene: Intimate vocal", "Scéna: Intimní zpěv" }, { "A doubled tonal voice with decorrelated breath and room. Close and wide, with sharp consonants.", "Zdvojený tónový hlas s dekorelovaným dechem a místností. Blízko a široce, s ostrými souhláskami." }, { "", "" }, { "", "" }, "" },
};

std::unordered_map<std::string, const Entry*>& index()
{
    static std::unordered_map<std::string, const Entry*> m = []
    {
        std::unordered_map<std::string, const Entry*> r;
        for (const auto& e : entries)
            r[e.key] = &e;
        for (const auto& e : presetEntries)
            r[e.key] = &e;
        return r;
    }();
    return m;
}

juce::String pick (const T& t, Language l) { return juce::String::fromUTF8 (l == Language::Czech ? t.cs : t.en); }
} // namespace

bool helpIn (const juce::String& key, Language l, Help& out)
{
    const auto it = index().find (key.toStdString());
    if (it == index().end())
        return false;
    const auto& e = *it->second;
    out = { pick (e.title, l), pick (e.what, l), pick (e.how, l), pick (e.tryThis, l), juce::String::fromUTF8 (e.ref), {} };
    deepIn (key, l, out.deep);
    return true;
}

bool help (const juce::String& key, Help& out) { return helpIn (key, language(), out); }
bool hasHelp (const juce::String& key) { return index().count (key.toStdString()) > 0; }

std::vector<juce::String> helpKeys()
{
    std::vector<juce::String> k;
    for (const auto& e : entries)
        k.emplace_back (e.key);
    for (const auto& e : presetEntries)
        k.emplace_back (e.key);
    return k;
}
} // namespace sph::ui
