// Learning content: the "In depth" sections of the info panel and the
// lessons of the Learn menu, in English and Czech.

#include "ui/InfoPanel.h"

#include "plugin/Parameters.h"

#include <unordered_map>

namespace sph::ui
{
namespace
{
struct Deep
{
    const char* key;
    const char* en;
    const char* cs;
};

// Longer explanations, shown below "Try this" as "In depth".
const Deep deepEntries[] = {
{ "p.width",
  "Width here is the level of the synthesised side, not a pan law. Doubling it raises the side by 6 dB. The correlation meter shows the result: the channels stay similar while the side is small against the mid, and become independent as it approaches the mid's level. Width above 100 % is useful when the generators are set gently and you want more of all of them at once. Past a certain point more side stops sounding wider and starts sounding hollow or unstable, which is why the correlation guard sits right after this control. Perceived width also depends on the playback: on loudspeakers each ear hears both speakers, which limits how wide anything can sound; on headphones the same signal can sound much wider.",
  "Šíře je zde úroveň syntetizované strany, ne panoramatický zákon. Její zdvojnásobení zvedne stranu o 6 dB. Výsledek ukazuje korelační měřič: dokud je strana proti středu malá, kanály zůstávají podobné, a čím víc se blíží úrovni středu, tím jsou nezávislejší. Šíře nad 100 % se hodí, když jsou generátory nastavené jemně a chcete víc ze všech najednou. Od určitého bodu už další strana nezní šířeji, ale dutě nebo nestabilně – proto hned za tímto prvkem stojí hlídač korelace. Vnímaná šíře závisí i na přehrávání: u reproduktorů slyší každé ucho oba reproduktory, což omezuje, jak široce cokoli může znít; ve sluchátkách tentýž signál zní mnohem šířeji." },
{ "p.mid_blend",
  "Every widening effect can be written as mid plus side. A classic Haas delay is L = x, R = x delayed: its mid is (x + delayed x) / 2, which is a comb filter, and its side is the difference. This plugin keeps only the side by default, so the mono sum is exactly the input. Mid blend gives back the mid part, so each effect sounds like its original hardware: a real Haas pair, a chorus heard in mono too. The cost is that mono listeners now hear the colouring. On a single instrument that may be fine or even wanted; on a mix bus or anything that will be played in mono, keep it at 0 %.",
  "Každý rozšiřovací efekt lze zapsat jako střed plus strana. Klasické Haasovo zpoždění je L = x, R = zpožděné x: jeho střed je (x + zpožděné x) / 2, tedy hřebenový filtr, a jeho strana je rozdíl. Tento plugin ve výchozím stavu ponechá jen stranu, takže mono součet je přesně vstup. Příměs středu vrátí i středovou část, takže efekt zní jako původní hardware: skutečný Haasův pár, chorus slyšitelný i v mono. Cenou je, že posluchači v mono teď slyší zabarvení. Na jednom nástroji to může být v pořádku, i žádoucí; na master sběrnici nebo u čehokoli, co se bude hrát v mono, ji nechte na 0 %." },
{ "p.bass_mono_hz",
  "Low frequencies have wavelengths of several metres, longer than the distance between the ears, so the ear can hardly tell where they come from; their width adds little to the image. They do carry most of the energy, though. Out-of-phase bass costs headroom, makes a vinyl cutting stylus move vertically (which mastering engineers avoid), and cancels on mono club systems, phone speakers and Bluetooth boxes. Keeping the side free of bass below about 100 to 200 Hz is standard practice in mixing and mastering. The filter here is a 24 dB/octave Linkwitz-Riley high-pass applied only to the synthesised side, so the dry bass, mono or not, passes untouched.",
  "Nízké kmitočty mají vlnovou délku několik metrů, delší než vzdálenost mezi ušima, takže ucho jen těžko pozná, odkud přicházejí; jejich šíře obrazu skoro nic nepřidá. Nesou ale většinu energie. Basy v protifázi ubírají rezervu, nutí řezací hrot vinylu kmitat svisle (čemuž se mastering vyhýbá) a ruší se na mono ozvučení v klubu, v reproduktoru telefonu i v bluetooth reproduktorech. Držet stranu bez basů pod zhruba 100 až 200 Hz je běžná praxe při mixu i masteringu. Filtr je zde horní propust Linkwitz-Riley 24 dB/okt. použitá jen na syntetizovanou stranu, takže suché basy, ať mono nebo ne, projdou beze změny." },
{ "p.transient_duck",
  "Attacks carry the information about where a sound is: the ear localises mostly by the first few milliseconds (the precedence effect). Decorrelators and delays spread an attack over time and between the speakers, which blurs the hit and pushes it away from the centre. Ducking the synthesised side for the length of the attack keeps the hit dry and centred while the sustain and the room behind it stay wide. This is how many mix engineers widen drums and percussion by hand, with transient shapers on the side channel. Too much ducking on dense, percussive material narrows everything, because the detector sees almost continuous attacks.",
  "Nástupy nesou informaci o tom, kde zvuk je: ucho lokalizuje hlavně podle prvních několika milisekund (efekt přednosti). Dekorelátory a zpoždění rozprostřou nástup v čase i mezi reproduktory, takže úder rozmažou a odsunou ze středu. Když se syntetizovaná strana po dobu nástupu ztlumí, úder zůstane suchý a uprostřed, zatímco doznívání a prostor za ním zůstanou široké. Takto mnoho zvukařů rozšiřuje bicí a perkuse ručně – transient shaperem na boční složce. Příliš silný útlum na hustém perkusivním materiálu zúží všechno, protože detektor vidí téměř nepřetržité nástupy." },
{ "p.guard",
  "Correlation is the normalised product of left and right averaged over time: +1 for identical channels, 0 for unrelated ones, -1 for one channel being the inverse of the other. In mid/side terms it equals (Pm - Ps) / (Pm + Ps), where Pm and Ps are the powers of mid and side. Negative correlation therefore means the side is louder than the mid: the image becomes phasey, seems to come from outside the speakers or from behind the head, and collapses badly in mono. Broadcasters and mastering engineers watch the correlation meter for exactly this. The guard computes Pm and Ps over 200 ms and reduces the side whenever it would exceed the ceiling, reacting within 5 ms and recovering over about 100 ms.",
  "Korelace je normovaný součin levého a pravého kanálu průměrovaný v čase: +1 pro shodné kanály, 0 pro nesouvisející, -1, když je jeden kanál převrácený druhý. V řeči středu a strany se rovná (Pm - Ps) / (Pm + Ps), kde Pm a Ps jsou výkony středu a strany. Záporná korelace tedy znamená, že strana je hlasitější než střed: obraz začne znít fázově, jako by přicházel zvenku reproduktorů nebo zezadu, a v mono se výrazně propadne. Právě kvůli tomu sledují korelační měřič (korelátor) rozhlasoví technici i masteringoví inženýři. Hlídač počítá Pm a Ps za 200 ms a stranu ztlumí, kdykoli by překročila strop; reaguje do 5 ms a vrací se během asi 100 ms." },
{ "p.guard_ceiling_db",
  "Adding side to a signal adds energy: the stereo output is louder by 10 log10 (1 + Ps / Pm) dB than the dry input, while the mono sum stays the same. Wider settings therefore also win blind comparisons simply by being louder, and loudness-normalised streaming turns the whole track down. The ceiling bounds this directly. At 0 dB the side may reach the mid (+3 dB at most, correlation 0); at -6 dB it stays at a quarter of the mid's power (+1 dB at most, correlation at least 0.6), which is still clearly wide on most material.",
  "Přidání strany přidává energii: stereo výstup je o 10 log10 (1 + Ps / Pm) dB hlasitější než suchý vstup, zatímco mono součet zůstává stejný. Širší nastavení proto vyhrávají i slepá porovnání jen tím, že jsou hlasitější, a streamovací služby s normalizací hlasitosti pak celou skladbu ztlumí. Strop tohle omezuje přímo. Při 0 dB smí strana dosáhnout úrovně středu (nejvýš +3 dB, korelace 0); při -6 dB zůstane na čtvrtině výkonu středu (nejvýš +1 dB, korelace aspoň 0,6), což na většině materiálu pořád zní zřetelně široce." },
{ "p.comp_mode",
  "Loudness bias is the most common trap when judging stereo processing: of two versions, the louder one usually sounds better, fuller and wider. Constant loudness divides out the energy the side adds, so you compare width with width. Because it scales the mid too, the mono sum is no longer identical to the input, only its spectrum is. Use it for listening and decisions, and Mono-exact for the final setting if mono compatibility matters.",
  "Zkreslení hlasitostí je nejčastější past při posuzování stereo zpracování: ze dvou verzí obvykle zní lépe, plněji a šířeji ta hlasitější. Stálá hlasitost vyruší energii, kterou strana přidá, takže porovnáváte šíři se šíří. Protože škáluje i střed, mono součet už není totožný se vstupem, jen jeho spektrum. Používejte ji pro poslech a rozhodování a pro konečné nastavení Přesné mono, pokud na mono kompatibilitě záleží." },
{ "p.listen",
  "Checking in mono is the single most useful habit in stereo work. Many playback situations are mono or nearly so: phone and laptop speakers, smart speakers, PA systems in clubs and venues, radio in cars and kitchens, and anyone standing far off-axis from a stereo pair. The Side position is the other half of the check: it isolates exactly what the plugin adds, so you can hear whether the side is smooth and musical or full of artefacts, and whether the bass and the attacks have stayed out of it.",
  "Kontrola v mono je nejužitečnější návyk při práci se stereem. Mnoho situací poslechu je mono nebo skoro mono: reproduktory telefonů a notebooků, chytré reproduktory, ozvučení v klubech a sálech, rádio v autě a v kuchyni a každý, kdo stojí daleko mimo osu stereo páru. Poloha Strana je druhá polovina kontroly: oddělí přesně to, co plugin přidává, takže uslyšíte, zda je strana hladká a hudební, nebo plná artefaktů, a zda v ní nezůstaly basy a nástupy." },
{ "p.engine",
  "The Light engine runs every generator in the time domain on the whole signal, with zero latency: right for tracking, live use and anything played in real time. The Full engine adds a short-time Fourier analysis that splits the sound into tonal, noise and transient parts and tracks individual partials. This enables generators that need to know what is playing: the Pan map places harmonics and sources, the coherence designer shapes similarity per band, the image expander repositions sources in a stereo mix, and every generator can be fed one component only, for example widening the room and the breaths of a vocal while the voice itself stays put. The price is one analysis frame of latency, which your host compensates.",
  "Lehké jádro zpracovává všechny generátory v časové oblasti na celém signálu s nulovou latencí – vhodné pro nahrávání, hraní naživo a vše v reálném čase. Plné jádro přidává krátkodobou Fourierovu analýzu, která rozloží zvuk na tónovou, šumovou a přechodovou (transientní) složku a sleduje jednotlivé parciály. Tím umožní generátory, které potřebují vědět, co hraje: panoramatická mapa rozmisťuje harmonické a zdroje, návrhář koherence tvaruje podobnost po pásmech, rozšíření stereobáze přesouvá zdroje ve stereo mixu a každý generátor může dostat jen jednu složku – například rozšířit prostor a nádechy zpěvu, zatímco hlas sám zůstane na místě. Cenou je latence jednoho analyzačního rámce, kterou hostitel vyrovná." },
{ "card.spread",
  "An all-pass filter changes only the phase of each frequency, not its level. Using an all-passed copy of the input as the side gives L = M + S and R = M - S with |S| = |M|: at each frequency the two channels differ only in phase, which the ear hears as a direction and as width. Because |L|^2 + |R|^2 is constant, the overall tone stays neutral, but each channel on its own is a comb: where L has a peak, R has a dip. That is why a spread sounds fine in stereo but can sound coloured when one speaker dominates, for example when you sit close to one side. Lauridsen's 1954 pseudo-stereo used a plain delay as the all-pass; Orban's 1970 design used a cascade of all-pass sections, which spreads the alternations smoothly over frequency and colours less.",
  "Všepropustný filtr mění jen fázi každého kmitočtu, ne jeho úroveň. Když se jako strana použije všepropustně upravená kopie vstupu, vznikne L = M + S a R = M - S s |S| = |M|: na každém kmitočtu se kanály liší jen fází, kterou ucho slyší jako směr a šíři. Protože |L|^2 + |R|^2 je stálé, celková barva zůstává neutrální, ale každý kanál sám je hřeben: kde má L vrchol, má R propad. Proto rozprostření zní ve stereu dobře, ale může znít zabarveně, když převládne jeden reproduktor – například když sedíte blízko jedné strany. Lauridsenovo pseudostereo z roku 1954 použilo jako všepropustný filtr prosté zpoždění; Orbanův návrh z roku 1970 kaskádu všepropustných článků, která střídání rozloží plynule po kmitočtech a zabarvuje méně." },
{ "card.delay",
  "When the same sound arrives twice within about 1 to 35 ms, the hearing fuses the two into one event and places it toward the earlier arrival: the precedence or Haas effect. Delaying one channel by a few milliseconds therefore moves the image toward the other speaker and makes it wider and more spacious. Above about 35 to 40 ms the copy becomes a separate echo. The problem is mono: summing a signal with its delayed copy is a comb filter, with notches every 1 / delay Hz. In mono-safe mode this generator adds only the difference to the side, which halves the depth of the effect but leaves the mono sum untouched. Lowering the low-pass makes the copy behave like a real wall reflection, which is duller than the direct sound.",
  "Když tentýž zvuk dorazí dvakrát s odstupem zhruba 1 až 35 ms, sluch je spojí v jednu událost a umístí ji ke straně, odkud přišel dřív: efekt přednosti, neboli Haasův efekt. Zpoždění jednoho kanálu o pár milisekund proto posune obraz k druhému reproduktoru a udělá ho širším a prostornějším. Nad zhruba 35 až 40 ms se z kopie stává samostatná ozvěna. Problémem je mono: součet signálu a jeho zpožděné kopie je hřebenový filtr se zářezy každých 1 / zpoždění Hz. V mono-kompatibilním režimu tento generátor přidá do strany jen rozdíl, což efektu ubere polovinu hloubky, ale mono součet nechá nedotčený. Snížením dolní propusti se kopie chová jako skutečný odraz od stěny, který je tmavší než přímý zvuk." },
{ "card.mod",
  "Two signals that differ slowly over time are heard as two sources rather than one: this is why an ensemble of voices sounds wider than one voice, even when they all sit in the centre. The chorus mode imitates the Roland Dimension: two short delays modulated in opposite directions, so that their sum stays constant while their difference moves. The micro-pitch mode imitates the Eventide doublers of the 1970s: one side a few cents sharp, the other a few cents flat, which makes the two channels beat slowly against each other. Both work best on sustained, tonal sounds; on percussion the movement is heard as flanging.",
  "Dva signály, které se v čase pomalu liší, slyšíme jako dva zdroje, ne jako jeden – proto soubor hlasů zní šířeji než jeden hlas, i když všichni stojí uprostřed. Režim chorus napodobuje Roland Dimension: dvě krátká zpoždění modulovaná opačným směrem, takže jejich součet je stálý, zatímco rozdíl se pohybuje. Režim mikrotransponování napodobuje harmonizéry Eventide ze 70. let: jedna strana o pár centů výš, druhá o pár centů níž, takže kanály proti sobě pomalu tvoří zázněje. Oba nejlépe fungují na držených tónových zvucích; na perkusích se pohyb slyší jako flanger." },
{ "card.velvet",
  "Decorrelation means giving the two channels the same spectrum and the same envelope but a different fine structure, so that they no longer move together sample by sample. The ear then hears a diffuse, enveloping sound, like an instrument heard in a room. The classic way is to convolve each channel with a different short noise burst. Velvet noise is a sparse version of that: only a few dozen impulses of +1 or -1 with gaps between them, which costs very little to compute and smears transients less than dense noise. The catch with any decorrelator is colouration: a short random filter is never perfectly flat. The optimised design searches offline for sequence pairs whose third-octave response stays within about 2 dB while the two sides stay almost uncorrelated.",
  "Dekorelace znamená dát oběma kanálům stejné spektrum a stejnou obálku, ale jinou jemnou strukturu, takže se už nepohybují spolu vzorek po vzorku. Ucho pak slyší difúzní, obklopující zvuk, jako nástroj slyšený v místnosti. Klasický způsob je provést konvoluci každého kanálu s jiným krátkým šumovým impulzem. Velvet noise (sametový šum) je jeho řídká verze: jen několik desítek impulzů +1 nebo -1 s mezerami mezi nimi, což stojí velmi málo výpočtu a rozmazává transienty méně než hustý šum. Háček každého dekorelátoru je zabarvení: krátký náhodný filtr nikdy není dokonale rovný. Optimalizovaný návrh předem hledá páry sekvencí, jejichž třetinooktávová odezva zůstane zhruba do 2 dB, zatímco obě strany zůstanou téměř nekorelované." },
{ "card.pan",
  "Spectral panning places different frequencies at different positions. In its oldest form, the complementary split, alternating frequency bands go to the left and to the right; it widens anything but can tear a single instrument apart, because its harmonics end up in different places. Tracks and Groups solve this with analysis. Tracks follows each partial over time and keeps it at a fixed position, so a sustained note does not jump. Groups goes further and gathers partials into sources the way the hearing does (auditory scene analysis): partials that start together and form a harmonic series belong to one instrument and get one position, so each instrument of a mono recording can be given its own place. The panning is coherent with the dry signal, so it moves sounds rather than blurring them.",
  "Spektrální panoráma umisťuje různé kmitočty na různá místa. V nejstarší podobě, doplňkovém rozdělení, jdou střídavá pásma kmitočtů vlevo a vpravo; rozšíří cokoli, ale jediný nástroj umí roztrhat, protože jeho harmonické skončí na různých místech. Režimy Stopy a Skupiny to řeší analýzou. Stopy sledují každý parciál v čase a drží ho na pevném místě, takže držený tón neskáče. Skupiny jdou dál a spojují parciály do zdrojů tak, jak to dělá sluch (analýza sluchové scény): parciály, které začnou spolu a tvoří harmonickou řadu, patří k jednomu nástroji a dostanou jedno místo, takže každý nástroj mono nahrávky může mít svou pozici. Panoráma je koherentní se suchým signálem, takže zvuky posouvá, ne rozmazává." },
{ "card.coherence",
  "Coherence is correlation measured per frequency band. Real stereo recordings are not equally similar at all frequencies: two microphones far apart pick up nearly the same bass (its wavelength is long) but very different highs. That frequency-dependent similarity is a large part of what makes a recording sound like a real space, and it is what simple wideners lack. The coherence designer sets the target per band, either from a curve you draw or from the formula of a real microphone pair, and then synthesises it: the dry mid plus or minus a decorrelated copy, with the gain solved per band from the measured signals so the result matches the target even on tonal material. Because the mid is untouched, the mono sum stays exact whatever the curve.",
  "Koherence je korelace měřená po kmitočtových pásmech. Skutečné stereo nahrávky nejsou na všech kmitočtech stejně podobné: dva mikrofony daleko od sebe zachytí téměř stejné basy (mají dlouhou vlnovou délku), ale velmi rozdílné výšky. Tahle na kmitočtu závislá podobnost je velkou částí toho, proč nahrávka zní jako skutečný prostor – a právě ta jednoduchým rozšiřovačům chybí. Návrhář koherence nastaví cíl pro každé pásmo, buď z křivky, kterou nakreslíte, nebo ze vzorce skutečného mikrofonního páru, a pak ho syntetizuje: suchý střed plus nebo minus dekorelovaná kopie, se ziskem počítaným po pásmech z naměřeného signálu, takže výsledek odpovídá cíli i na tónovém materiálu. Protože střed zůstává nedotčen, mono součet je přesný, ať je křivka jakákoli." },
{ "card.double",
  "Double tracking means recording the same part twice and playing both takes together, often panned apart. The two takes are never identical: timing differs by a few milliseconds and wanders, pitch differs by a few cents, level and tone differ slightly. That random, unrepeating difference is what makes doubled vocals and guitar walls sound thick and wide. Artificial double tracking, invented at Abbey Road in 1966, imitated it with a tape delay whose speed was varied by hand. This generator does the same with two synthetic takes, each reading the input at its own slowly drifting delay, so the movement never repeats the way a chorus does.",
  "Zdvojení stopy (double tracking) znamená nahrát stejný part dvakrát a přehrát oba záznamy spolu, často rozložené do stran. Dva záznamy nejsou nikdy stejné: načasování se liší o pár milisekund a toulá se, ladění o pár centů, úroveň i barva mírně. Právě tenhle náhodný, neopakující se rozdíl dělá zdvojené zpěvy a kytarové stěny hustými a širokými. Umělé zdvojení (ADT), vynalezené v Abbey Road roku 1966, ho napodobovalo páskovým zpožděním, jehož rychlost se měnila ručně. Tento generátor dělá totéž se dvěma syntetickými záznamy; každý čte vstup s vlastním pomalu se měnícím zpožděním, takže se pohyb nikdy neopakuje jako u chorusu." },
{ "card.room",
  "In a real room the direct sound is followed within a few tens of milliseconds by early reflections from the walls, floor and ceiling. Reflections from the sides reach the two ears differently, and that difference is the strongest single cue for apparent source width: concert-hall research of the 1960s and 70s showed that halls with strong early lateral reflections are heard as wide and enveloping. This generator computes those reflections with an image-source model of a rectangular room and records them with a virtual ORTF pair placed off-centre, as a listener never sits exactly in the middle. Without a reverb tail it adds width and depth that do not wash out the mix.",
  "Ve skutečné místnosti následují po přímém zvuku během několika desítek milisekund časné odrazy od stěn, podlahy a stropu. Odrazy z boků dorazí ke každému uchu jinak a tento rozdíl je nejsilnějším jednotlivým vodítkem pro vnímanou šíři zdroje: výzkum koncertních sálů v 60. a 70. letech ukázal, že sály se silnými časnými bočními odrazy znějí široce a obklopujícím dojmem. Tento generátor tyto odrazy počítá modelem zrcadlových zdrojů pravoúhlé místnosti a snímá je virtuálním párem ORTF mimo střed, protože posluchač nikdy nesedí přesně uprostřed. Bez dozvuku přidá šíři a hloubku, které mix nerozmáznou." },
{ "card.image",
  "A plain width control on a stereo mix scales the whole side: panned sources move outward, but so does everything that was already wide, and at high settings sources pass beyond the speakers and turn phasey. The image expander analyses the mix per frequency and estimates, for each bin, where it is panned and how much of it is diffuse. Panned components are moved outward along a curve that stops at the speaker, so nothing goes out of phase; the diffuse part (room, reverb, decorrelated layers) is scaled separately. This is the approach of the upmixing and stereo-enhancement research of the early 2000s.",
  "Prostý ovladač šíře na stereo mixu škáluje celou stranu: panorámované zdroje se posunou ven, ale také vše, co už bylo široké, a při velkých hodnotách se zdroje dostanou za reproduktory a začnou znít fázově. Rozšíření stereobáze analyzuje mix po kmitočtech a pro každý bin odhadne, kam je panorámovaný a jak velká jeho část je difúzní. Panorámované složky se posouvají ven po křivce, která se zastaví u reproduktoru, takže nic nejde do protifáze; difúzní část (místnost, dozvuk, dekorelované vrstvy) se škáluje zvlášť. To je přístup výzkumu upmixu a stereo zlepšování z počátku 21. století." },
{ "disp.goniometer",
  "The goniometer, also called a vectorscope or phase scope, plots every sample pair as a point, rotated by 45 degrees so that mid points up and side points sideways. Mono is a vertical line. A source panned left leans the line toward L. A spread or a delay opens the line into a narrow ellipse, decorrelation into a round, fuzzy cloud. A horizontal line or a shape wider than it is tall means more side than mid: negative correlation, a warning sign. Watching the shape while you adjust a widener tells you more than the sound alone about what kind of width you are adding.",
  "Goniometr, nazývaný také vektorskop nebo fázový osciloskop, vykreslí každý pár vzorků jako bod, otočený o 45 stupňů tak, aby střed mířil nahoru a strana do stran. Mono je svislá čára. Zdroj panorámovaný vlevo nakloní čáru k L. Rozprostření nebo zpoždění otevře čáru do úzké elipsy, dekorelace do kulatého rozmazaného mraku. Vodorovná čára nebo tvar širší než vyšší znamená víc strany než středu: zápornou korelaci, varovný signál. Sledovat tvar při nastavování rozšiřovače řekne o tom, jakou šíři přidáváte, víc než samotný zvuk." },
{ "disp.correlation",
  "A correlation meter (often called a correlator in Czech studios) is standard equipment in broadcast and mastering. Rules of thumb: near +1 the signal is close to mono; between about +0.3 and +0.8 is typical of a healthy stereo mix; around 0 means very wide, decorrelated material; a steady reading below 0 means phase problems, a polarity flip or an over-widened image that will fall apart in mono. Short dips below 0 on reverb tails or effects are normal. The meter here uses a 100 ms window, so it follows the music closely.",
  "Korelační měřič (v českých studiích často korelátor) je standardní výbava rozhlasu a masteringu. Orientační pravidla: blízko +1 je signál skoro mono; zhruba mezi +0,3 a +0,8 je typický zdravý stereo mix; kolem 0 znamená velmi široký, dekorelovaný materiál; trvale pod 0 znamená fázové problémy, převrácenou polaritu nebo přehnaně rozšířený obraz, který se v mono rozpadne. Krátké poklesy pod 0 na dozvucích nebo efektech jsou normální. Měřič zde používá okno 100 ms, takže hudbu sleduje těsně." },
{ "disp.asw",
  "Apparent source width (ASW) is the impression that a sound occupies a broad region rather than a point. Concert-hall acoustics links it to the interaural cross-correlation (IACC): how similar the signals at the two eardrums are, allowing for the up to 1 ms of delay the head introduces. Low IACC in the 500 Hz to 2 kHz octaves means a wide sound. This meter simulates that: a spherical head model in front of two loudspeakers at plus and minus 30 degrees (or wearing headphones) computes the ear signals, and the reading is 1 minus their correlation. It explains two everyday facts: the same mix sounds wider on headphones, because each ear hears only one channel, and on speakers making the channels ever more different eventually stops adding width, because each ear hears both speakers anyway.",
  "Vnímaná šíře zdroje (ASW) je dojem, že zvuk zabírá širokou oblast, ne bod. Akustika koncertních sálů ji spojuje s mezioušní vzájemnou korelací (IACC): jak podobné jsou signály u obou bubínků, s ohledem na zpoždění až 1 ms, které způsobí hlava. Nízká IACC v oktávách 500 Hz až 2 kHz znamená široký zvuk. Tento měřič to simuluje: model kulové hlavy před dvěma reproduktory na plus a minus 30 stupních (nebo se sluchátky) spočítá signály v uších a údaj je 1 minus jejich korelace. Vysvětluje dvě každodenní zkušenosti: stejný mix zní šířeji ve sluchátkách, protože každé ucho slyší jen jeden kanál, a na reproduktorech přestane další odlišování kanálů od určité míry šíři přidávat, protože každé ucho stejně slyší oba reproduktory." },
{ "disp.bands",
  "Width is rarely the same at all frequencies, and problems usually hide in one region: a phasey low mid, a fizzy top, a bass that is wide when it should not be. The upper half of this view shows the correlation of each third-octave band, the lower half how the mono sum in that band differs from the dry input. With mid blend at 0 % the lower half must be a flat line at 0 dB; any comb or dip there is what mono listeners would hear.",
  "Šíře je málokdy na všech kmitočtech stejná a problémy se obvykle schovávají v jedné oblasti: fázové nízké středy, šumivé výšky, basy široké tam, kde nemají být. Horní polovina zobrazení ukazuje korelaci každého třetinooktávového pásma, dolní polovina, jak se mono součet v tom pásmu liší od suchého vstupu. Při příměsi středu 0 % musí být dolní polovina rovná čára na 0 dB; každý hřeben nebo propad tam je to, co by slyšeli posluchači v mono." },
{ "ui.easy",
  "Easy mode is a mapping, not a separate effect. Width sets the level of the synthesised side along a curve that was fitted by rendering a corpus of test material through the plugin and measuring the perceived width with the virtual listener, so that equal steps of the knob give roughly equal steps of width. Character decides which generators share that width, Space adds reflections and spaces the virtual microphones, Focus keeps the centre solid. All of it stays within limits on mono compatibility, correlation, loudness and bass, and the material classifier blends curves fitted for percussive, tonal and mixed material. Percussive material reaches less width by design, because its hits are kept centred.",
  "Snadný režim je mapování, ne samostatný efekt. Šíře nastavuje úroveň syntetizované strany po křivce, která vznikla tak, že se zkušební materiál prohnal pluginem a vnímaná šíře se měřila virtuálním posluchačem – stejné kroky knoflíku tak dávají přibližně stejné kroky šíře. Charakter rozhoduje, které generátory se o tu šíři podělí, Prostor přidá odrazy a rozestoupí virtuální mikrofony, Fokus drží střed pevný. To vše zůstává v mezích mono kompatibility, korelace, hlasitosti a basů a klasifikátor materiálu míchá křivky naladěné pro perkusivní, tónový a smíšený materiál. Perkusivní materiál záměrně dosáhne menší šíře, protože jeho údery zůstávají uprostřed." },
{ "p.easy_character",
  "The three families make three different kinds of stereo, and they are worth hearing separately. Phase-based width (low Character) keeps every sound exactly where it is in time, so it stays focused and transparent, but it can sound a little synthetic on sustained tones. Decorrelation (around 50 %) sounds most like a real room and real microphones: diffuse and natural, at the cost of some softening of attacks. Movement (high Character) imitates two performers or double-tracked takes: lively and thick, ideal for vocals, guitars and pads, less so for anything that must stay tight.",
  "Tři rodiny vytvářejí tři různé druhy sterea a stojí za to slyšet je zvlášť. Fázová šíře (nízký Charakter) nechá každý zvuk přesně tam, kde je v čase, takže zůstane soustředěný a průzračný, ale na držených tónech může znít trochu synteticky. Dekorelace (kolem 50 %) zní nejvíc jako skutečná místnost a skutečné mikrofony: difúzně a přirozeně, za cenu jistého změkčení nástupů. Pohyb (vysoký Charakter) napodobuje dva hráče nebo zdvojené záznamy: živě a hustě, ideální pro zpěvy, kytary a plochy, méně pro vše, co musí zůstat sevřené." },
{ "p.easy_focus",
  "Focus encodes a rule that mix engineers follow almost universally: keep the elements that carry the energy and the rhythm in the centre, and widen the rest. Kick, bass and the attack of the snare stay mono so the low end is solid and the groove is punchy on any system; the sustain, the room and the high frequencies can be wide. At 0 % some protection remains, so that loudness and bass stay within bounds.",
  "Fokus vyjadřuje pravidlo, které zvukaři dodržují téměř všude: prvky, které nesou energii a rytmus, držet uprostřed a rozšiřovat zbytek. Kopák, basa a nástup virblu zůstávají mono, aby byly basy pevné a groove úderný na jakémkoli zařízení; doznívání, prostor a výšky mohou být široké. I na 0 % zůstane část ochrany, aby hlasitost a basy zůstaly v mezích." },
{ "p.coh_mode",
  "Each classic microphone pair has a characteristic coherence curve, and with it a characteristic sound. Spaced omnis (AB) are coherent in the bass and decorrelated above c / (2 d): spacious, but with a soft centre and less precise localisation. Coincident pairs (XY, Blumlein) put both capsules at one point, so they have no time differences at all and the same coherence at every frequency: precise images, mono-compatible, and in the Blumlein case fully decorrelated diffuse sound. Near-coincident pairs such as ORTF (17 cm, 110 degrees) mix both: some time difference, some level difference, a balance used by broadcasters for decades.",
  "Každý klasický mikrofonní pár má charakteristickou křivku koherence a s ní charakteristický zvuk. Rozložené kulové mikrofony (AB) jsou koherentní v basech a nad c / (2 d) dekorelované: prostorné, ale s měkčím středem a méně přesnou lokalizací. Koincidenční páry (XY, Blumlein) mají obě kapsle v jednom bodě, takže nemají vůbec žádné časové rozdíly a na všech kmitočtech stejnou koherenci: přesný obraz, mono kompatibilita a u Blumleina plně dekorelovaný difúzní zvuk. Blízce koincidenční páry jako ORTF (17 cm, 110 stupňů) kombinují obojí: trochu časového a trochu úrovňového rozdílu – kompromis, který rozhlas používá desítky let." },
{ "p.latency_mode",
  "A plugin's latency is reported to the host, which delays every other track by the same amount so that everything stays in time. When the latency changes, the host has to re-align, which in many hosts causes a gap or a click and in some is only picked up when playback restarts. Always Full keeps the reported latency constant, so you can switch engines freely while the transport runs.",
  "Latence pluginu se hlásí hostiteli, který o stejnou dobu zpozdí všechny ostatní stopy, aby vše zůstalo v čase. Když se latence změní, hostitel musí znovu zarovnat, což v mnoha hostitelích způsobí výpadek nebo lupnutí a v některých se projeví až po novém spuštění přehrávání. Vždy plná drží hlášenou latenci stálou, takže lze přepínat jádra za chodu přehrávání." },
{ "disp.material",
  "The classifier listens to what is coming in, independently of the engine and without latency. It counts onsets where most frequencies rise at once (hits, as opposed to new notes) and measures how much of the energy sits in steady spectral peaks (notes, as opposed to noise). Drums score high on the first, sustained instruments on the second, full mixes on both. The weights move slowly on purpose: the mapping should follow the character of a passage, never a single hit.",
  "Klasifikátor poslouchá, co přichází, nezávisle na jádru a bez latence. Počítá nástupy, při nichž stoupá většina kmitočtů zároveň (údery, na rozdíl od nových tónů), a měří, jaká část energie leží ve stálých spektrálních vrcholech (tóny, na rozdíl od šumu). Bicí mají vysoké skóre v prvním, držené nástroje ve druhém, celé mixy v obou. Váhy se mění záměrně pomalu: mapování má sledovat charakter pasáže, nikdy jeden úder." },
};

const std::unordered_map<std::string, const Deep*>& deepIndex()
{
    static const std::unordered_map<std::string, const Deep*> m = []
    {
        std::unordered_map<std::string, const Deep*> r;
        for (const auto& d : deepEntries)
            r[d.key] = &d;
        return r;
    }();
    return m;
}
} // namespace

bool deepIn (const juce::String& key, Language l, juce::String& out)
{
    const auto it = deepIndex().find (key.toStdString());
    if (it == deepIndex().end())
        return false;
    out = juce::String::fromUTF8 (l == Language::Czech ? it->second->cs : it->second->en);
    return true;
}

std::vector<juce::String> deepKeys()
{
    std::vector<juce::String> k;
    for (const auto& d : deepEntries)
        k.emplace_back (d.key);
    return k;
}

// ------------------------------------------------------------------ lessons

const std::vector<Tour>& tours()
{
    static const std::vector<Tour> t {
        { "How we hear width", "Jak slyšíme šíři", {
            { "Your two ears sit about 17 cm apart, with a head in between. A sound from the left reaches the left ear first (up to about 0.7 ms earlier) and louder, especially at high frequencies, which the head shadows. These two cues, the interaural time difference and the interaural level difference, are how you hear direction.",
              "Vaše uši jsou od sebe asi 17 cm a mezi nimi je hlava. Zvuk zleva dorazí k levému uchu dřív (až asi o 0,7 ms) a silnější, hlavně na vysokých kmitočtech, které hlava stíní. Tato dvě vodítka, mezioušní časový a mezioušní úrovňový rozdíl, jsou to, podle čeho slyšíte směr.", { "disp.goniometer" }, {} },
            { "Two loudspeakers create a phantom image between them by sending the same signal with small differences of level or time. Pan a mono signal and the image moves; send identical signals and it sits in the middle, although nothing comes from there.",
              "Dva reproduktory vytvoří mezi sebou fantomový obraz tím, že vysílají stejný signál s malými rozdíly úrovně nebo času. Panorámujte mono signál a obraz se posune; pošlete shodné signály a sedí uprostřed, i když odtamtud nic nevychází.", { "disp.goniometer" }, {} },
            { "Width is something else than direction. A sound seems wide when the signals at your two ears are dissimilar, as when a violin is heard in a hall: the direct sound comes from one place, but early reflections from the side walls arrive at each ear differently. Acousticians measure this as the interaural cross-correlation (IACC); the lower it is, the wider the sound.",
              "Šíře je něco jiného než směr. Zvuk se zdá široký, když se signály v obou uších liší, jako když houslisty slyšíte v sále: přímý zvuk přichází z jednoho místa, ale časné odrazy od bočních stěn dorazí ke každému uchu jinak. Akustici to měří jako mezioušní vzájemnou korelaci (IACC); čím je nižší, tím širší zvuk je.", { "disp.asw" }, {} },
            { "So every stereo widener does one of two things: it moves parts of the sound to different places (panning, spectral panning, Haas delays), or it makes the two channels less alike (phase, decorrelation, modulation, reflections). The perceived-width meter estimates the second effect the way a listener would hear it.",
              "Každý stereo rozšiřovač tedy dělá jednu ze dvou věcí: přesouvá části zvuku na různá místa (panoráma, spektrální panoráma, Haasovo zpoždění), nebo dělá kanály méně podobnými (fáze, dekorelace, modulace, odrazy). Měřič vnímané šíře odhaduje ten druhý účinek tak, jak by ho slyšel posluchač.", { "disp.asw" }, {} },
            { "Switch the meter between Speakers and Headphones. On speakers each ear also hears the opposite speaker (crosstalk), which limits how wide anything can sound; on headphones each ear hears only its own channel. That is why a mix that sounds just right on headphones often sounds narrow on speakers, and a mix that is wide on speakers can sound exaggerated on headphones.",
              "Přepínejte měřič mezi Reproduktory a Sluchátky. U reproduktorů slyší každé ucho i protější reproduktor (přeslech), což omezuje, jak široce cokoli může znít; ve sluchátkách slyší každé ucho jen svůj kanál. Proto mix, který zní akorát ve sluchátkách, často zní na reproduktorech úzce, a mix široký na reproduktorech může ve sluchátkách znít přehnaně.", { "disp.asw" }, {} } } },
        { "Mid and side", "Střed a strana", {
            { "Stereo can be described as left and right, or as mid (L + R, what both share) and side (L - R, what differs). The two descriptions hold the same information; mid/side, or M/S, is simply a more useful view for widening. This plugin never touches the mid: it only adds side.",
              "Stereo lze popsat jako levý a pravý kanál, nebo jako střed (L + R, co mají společné) a stranu (L - R, čím se liší). Oba popisy nesou tutéž informaci; mid/side, neboli M/S, je jen užitečnější pohled pro rozšiřování. Tento plugin střed nikdy nemění: jen přidává stranu.", { "disp.goniometer" }, {} },
            { "On the goniometer, mid points straight up and side points sideways. A mono signal is a vertical line.",
              "Na goniometru střed míří nahoru a strana do stran. Mono signál je svislá čára.", { "disp.goniometer" }, { { ids::spread_amount, 0 } } },
            { "Raise the Spread amount: the line opens into a shape leaning left and right. That opening is the side signal.",
              "Zvyšte množství rozprostření: čára se otevře do tvaru nakloněného vlevo a vpravo. To otevření je boční signál.", { "p.spread_amount", "disp.goniometer" }, { { ids::spread_amount, 80 } } },
            { "Width scales all the side at once. The correlation meter shows how similar the channels stay: +1 is mono, 0 is fully different. Mastering engineers use the same mid/side view with M/S equalisers and compressors: they can brighten only the side, or narrow only the bass.",
              "Šíře škáluje celou stranu najednou. Korelační měřič ukazuje, jak podobné kanály zůstávají: +1 je mono, 0 zcela odlišné. Masteringoví inženýři používají stejný pohled střed/strana v M/S ekvalizérech a kompresorech: mohou zjasnit jen stranu nebo zúžit jen basy.", { "p.width", "disp.correlation" }, {} } } },
        { "Mono compatibility", "Mono kompatibilita", {
            { "Many listeners hear mono: phones, laptop and smart speakers, kitchen radios, club PA systems, anyone far off to one side. Mono is (L + R) / 2, which cancels the side completely.",
              "Mnoho posluchačů slyší mono: telefony, reproduktory notebooků a chytré reproduktory, kuchyňská rádia, ozvučení v klubech, kdokoli daleko stranou. Mono je (L + R) / 2, což stranu úplně vyruší.", { "p.listen" }, {} },
            { "Set Listen to Mono and turn Width up and down: nothing changes, because the mid is untouched. That is what mono-safe means, and it holds for every generator in this plugin as long as Mid blend stays at 0 %.",
              "Přepněte Poslech na Mono a měňte Šíři: nic se nezmění, protože střed je nedotčen. To znamená mono-kompatibilní a platí to pro každý generátor tohoto pluginu, dokud Příměs středu zůstane na 0 %.", { "p.listen", "p.width" }, { { ids::listen, 1 } } },
            { "Mid blend adds each effect's mid part back. It sounds richer in stereo, but in mono you now hear combs and chorusing. The Bands view shows the mono-fold deviation.",
              "Příměs středu vrací do středu složku každého efektu. Ve stereu zní bohatěji, ale v mono teď slyšíte hřebeny a chorus. Zobrazení Pásma ukazuje odchylku mono součtu.", { "p.mid_blend", "tab.bands" }, { { ids::mid_blend, 100 }, { ids::listen, 1 } } },
            { "Return Mid blend to 0 % and Listen to Stereo. A good habit: check every widening decision in mono and on small speakers before you commit to it.",
              "Vraťte Příměs středu na 0 % a Poslech na Stereo. Dobrý návyk: každé rozhodnutí o šíři ověřte v mono a na malých reproduktorech, než se pro ně rozhodnete.", { "p.mid_blend" }, { { ids::mid_blend, 0 }, { ids::listen, 0 } } } } },
        { "A map of widening", "Mapa rozšiřování", {
            { "Panning and level: moving a mono sound left or right gives direction, not width. Two different sounds panned apart make a wide mix, which is why arrangement is the first and best widener.",
              "Panoráma a úroveň: posunutí mono zvuku vlevo nebo vpravo dá směr, ne šíři. Dva různé zvuky rozložené do stran dají široký mix – proto je aranžmá první a nejlepší rozšiřovač.", { "disp.goniometer" }, {} },
            { "Time: a short delay between the channels (Haas) moves and widens the image; in mono it becomes a comb filter. See the Delay card.",
              "Čas: krátké zpoždění mezi kanály (Haas) posune a rozšíří obraz; v mono se z něj stane hřebenový filtr. Viz karta Zpoždění.", { "card.delay" }, {} },
            { "Phase: an all-pass side signal makes the channels differ in phase per frequency while their sum stays flat (Lauridsen, Orban). Clean and mono-safe. See Spread.",
              "Fáze: všepropustný boční signál způsobí, že se kanály liší fází po kmitočtech, zatímco jejich součet zůstane rovný (Lauridsen, Orban). Čisté a mono-kompatibilní. Viz Rozprostření.", { "card.spread" }, {} },
            { "Movement: chorus, micro-pitch and double tracking make the channels differ slowly over time, like two performers. See Mod and Double.",
              "Pohyb: chorus, mikrotransponování a zdvojení stopy způsobí, že se kanály pomalu v čase liší, jako dva hráči. Viz Modulace a Zdvojení.", { "card.mod", "card.double" }, {} },
            { "Decorrelation and space: noise convolution, virtual microphone pairs and early reflections give the two channels a different fine structure, like a room does. See Velvet, Coherence and Room.",
              "Dekorelace a prostor: konvoluce se šumem, virtuální mikrofonní páry a časné odrazy dají kanálům jinou jemnou strukturu, jako to dělá místnost. Viz Velvet, Koherence a Prostor.", { "card.velvet", "card.coherence", "card.room" }, {} },
            { "Spectrum: different frequencies or different instruments placed at different positions. See Pan map. For stereo material, the image expander moves existing sources outward instead of adding anything new.",
              "Spektrum: různé kmitočty nebo různé nástroje umístěné na různá místa. Viz Panoramatická mapa. U stereo materiálu rozšíření stereobáze posouvá existující zdroje ven, místo aby přidávalo něco nového.", { "card.pan" }, {} } } },
        { "Haas and comb filters", "Haas a hřebenové filtry", {
            { "A copy delayed by a few milliseconds is fused with the original and heard from the earlier side: the precedence effect, described by Helmut Haas in 1951.",
              "Kopie zpožděná o pár milisekund splyne s originálem a je slyšet ze strany, která přišla dřív: efekt přednosti, který popsal Helmut Haas roku 1951.", { "card.delay" }, { { ids::spread_amount, 0 }, { ids::delay_amount, 100 }, { ids::mid_blend, 100 } } },
            { "Adding a signal to its delayed copy makes a comb filter: notches every 1 / delay Hz. Hover the Delay time to see the spacing.",
              "Součet signálu s jeho zpožděnou kopií vytvoří hřebenový filtr: zářezy každých 1 / zpoždění Hz. Najeďte na čas zpoždění a uvidíte rozestup.", { "p.delay_time_ms" }, {} },
            { "Listen in Mono now: the comb is plainly audible, a hollow, phasey colour. This is why classic Haas widening fails in mono.",
              "Poslouchejte teď v mono: hřeben je zřetelně slyšet jako dutá, fázová barva. Proto klasické Haasovo rozšíření v mono selhává.", { "p.listen" }, { { ids::listen, 1 } } },
            { "Set Mid blend to 0 %: the comb leaves the mono sum and lives only in the side. Half the depth, but mono-safe.",
              "Nastavte Příměs středu na 0 %: hřeben opustí mono součet a zůstane jen ve straně. Poloviční hloubka, ale mono-kompatibilní.", { "p.mid_blend" }, { { ids::mid_blend, 0 } } } } },
        { "Decorrelation", "Dekorelace", {
            { "Two signals with the same spectrum but different fine structure sound wide and diffuse. Measuring how similar they are gives the coherence.",
              "Dva signály se stejným spektrem, ale jinou jemnou strukturou zní široce a difúzně. Míra jejich podobnosti je koherence.", { "disp.correlation" }, {} },
            { "Velvet convolves each side with a different sparse click sequence. Watch the correlation fall.",
              "Velvet provede konvoluci každé strany s jinou řídkou sekvencí impulzů. Sledujte, jak korelace klesá.", { "card.velvet", "disp.correlation" }, { { ids::spread_amount, 0 }, { ids::velvet_amount, 100 } } },
            { "The coherence designer lets you choose the coherence per frequency, for example that of two microphones 40 cm apart (Full engine).",
              "Návrhář koherence vám dovolí zvolit koherenci po kmitočtech, například jako u dvou mikrofonů 40 cm od sebe (plné jádro).", { "card.coherence", "tab.coherence" }, { { ids::engine, 1 }, { ids::velvet_amount, 0 }, { ids::coh_amount, 100 }, { ids::coh_mode, 1 } } },
            { "The perceived-width meter shows the catch: on speakers, crosstalk between the ears limits how wide anything can sound. Beyond that point more decorrelation only softens the attacks and blurs the image.",
              "Měřič vnímané šíře ukazuje háček: na reproduktorech přeslech mezi ušima omezuje, jak široce cokoli může znít. Za tímto bodem další dekorelace jen změkčuje nástupy a rozmazává obraz.", { "disp.asw" }, {} } } },
        { "Microphone pairs", "Mikrofonní páry", {
            { "Recording engineers have made stereo with two microphones since the 1930s, and each arrangement has its own sound. The coherence designer can imitate the most common ones. This tour switches to the Full engine.",
              "Zvukaři natáčejí stereo dvěma mikrofony od 30. let a každé uspořádání má svůj zvuk. Návrhář koherence umí napodobit ty nejběžnější. Tato prohlídka přepne na plné jádro.", { "card.coherence" }, { { ids::engine, 1 }, { ids::spread_amount, 0 }, { ids::coh_amount, 100 }, { ids::coh_mode, 1 }, { ids::coh_spacing_cm, 40 } } },
            { "AB: two omnidirectional microphones a distance apart. Bass reaches both almost equally, highs do not: coherence falls with frequency. Spacious and natural. Widen the spacing and watch the curve's first zero move down.",
              "AB: dva kulové mikrofony v určité vzdálenosti. Basy k oběma dorazí skoro stejně, výšky ne: koherence s kmitočtem klesá. Prostorné a přirozené. Zvětšete rozestup a sledujte, jak se první nula křivky posouvá dolů.", { "p.coh_spacing_cm", "tab.coherence" }, { { ids::coh_spacing_cm, 100 } } },
            { "XY: two cardioids at one point, angled apart. No time difference at all, so the coherence is the same at every frequency. Precise and very mono-compatible.",
              "XY: dvě ledviny v jednom bodě, natočené od sebe. Žádný časový rozdíl, takže koherence je na všech kmitočtech stejná. Přesné a velmi mono-kompatibilní.", { "p.coh_mode", "p.coh_pattern" }, { { ids::coh_mode, 2 }, { ids::coh_pattern, 2 }, { ids::coh_angle_deg, 90 } } },
            { "Blumlein: two figure-8 microphones crossed at 90 degrees, as patented by Alan Blumlein in 1931 along with mid/side itself. Diffuse sound arrives fully decorrelated: very open and enveloping.",
              "Blumlein: dva osmičkové mikrofony zkřížené pod 90 stupni, jak je roku 1931 patentoval Alan Blumlein spolu se samotným principem středu a strany. Difúzní zvuk dorazí plně dekorelovaný: velmi otevřené a obklopující.", { "p.coh_pattern" }, { { ids::coh_pattern, 4 } } },
            { "ORTF: cardioids 17 cm apart at 110 degrees, the French broadcasting standard. A little time difference and a little level difference: a balanced middle ground.",
              "ORTF: ledviny 17 cm od sebe pod 110 stupni, francouzský rozhlasový standard. Trochu časového a trochu úrovňového rozdílu: vyvážená střední cesta.", { "p.coh_mode" }, { { ids::coh_mode, 3 }, { ids::coh_pattern, 2 }, { ids::coh_angle_deg, 110 }, { ids::coh_spacing_cm, 17 } } } } },
        { "Spectral panning", "Spektrální panoráma", {
            { "Switch the teaching source to Two sources from the settings menu, then apply this step.",
              "Přepněte v nastavení výukový zdroj na Dva zdroje a pak použijte tento krok.", { "card.pan" }, { { ids::engine, 1 }, { ids::spread_amount, 0 }, { ids::pan_amount, 100 }, { ids::pan_mode, 0 }, { ids::pan_depth, 100 } } },
            { "Static mode splits the spectrum into zones panned alternately left and right. See them on the Pan map tab. Notice how one instrument is torn apart: its harmonics land in different zones.",
              "Statický režim rozdělí spektrum na pásma střídavě vlevo a vpravo. Uvidíte je na kartě Pan. mapa. Všimněte si, jak se jeden nástroj roztrhá: jeho harmonické padnou do různých pásem.", { "tab.pan", "p.pan_density" }, {} },
            { "Groups mode finds the harmonics of each source and gives each source one position: two instruments, two places.",
              "Režim Skupiny najde harmonické každého zdroje a dá každému zdroji jednu pozici: dva nástroje, dvě místa.", { "p.pan_mode", "tab.pan" }, { { ids::pan_mode, 2 } } } } },
        { "Widening in a mix", "Rozšiřování v mixu", {
            { "Widen what supports, keep centred what leads. Pads, backing vocals, rhythm guitars, room mics and effects are the usual candidates; the lead vocal, kick, snare and bass usually stay in the middle, where they are strongest on every system.",
              "Rozšiřujte to, co podporuje, a uprostřed nechte to, co vede. Obvyklými kandidáty jsou plochy, doprovodné vokály, rytmické kytary, prostorové mikrofony a efekty; hlavní zpěv, kopák, virbl a basa obvykle zůstávají uprostřed, kde jsou na každém zařízení nejsilnější.", { "p.bass_mono_hz", "p.transient_duck" }, {} },
            { "Contrast makes width. If everything is wide, nothing is: a narrow verse makes a wide chorus feel bigger. Automating width between sections often does more than any setting.",
              "Šíři dělá kontrast. Když je široké všechno, není široké nic: úzká sloka udělá široký refrén větším. Automatizace šíře mezi částmi skladby často udělá víc než jakékoli nastavení.", { "p.width" }, {} },
            { "Keep the low end mono and the attacks centred. Bass mono and transient ducking do this automatically.",
              "Basy držte mono a nástupy uprostřed. Mono basy a útlum transientů to dělají samy.", { "p.bass_mono_hz", "p.transient_duck" }, {} },
            { "Compare at equal loudness. Wider is louder, and louder seems better. Use Constant loudness or the A / B compare with matched levels before deciding.",
              "Porovnávejte při stejné hlasitosti. Širší je hlasitější a hlasitější se zdá lepší. Než se rozhodnete, použijte Stálou hlasitost nebo porovnání A / B s vyrovnanými úrovněmi.", { "p.comp_mode", "ui.ab" }, {} },
            { "Check the translation: mono, small speakers, headphones and, if you can, a reference track you know well. The correlation meter should stay mostly positive.",
              "Ověřte přenositelnost: mono, malé reproduktory, sluchátka a pokud můžete, referenční skladbu, kterou dobře znáte. Korelační měřič by měl zůstávat převážně v kladných hodnotách.", { "p.listen", "disp.correlation" }, {} } } },
        { "Easy mode", "Snadný režim", {
            { "Easy mode turns the whole plugin into four macros. Width sets how wide; even steps of the knob give roughly even steps of perceived width.",
              "Snadný režim promění celý plugin ve čtyři makra. Šíře určuje, jak široce to zní; stejné kroky knoflíku dávají přibližně stejné kroky vnímané šíře.", { "p.easy_width" }, {} },
            { "Character chooses how the width is made: clean phase at 0 %, natural decorrelation at 50 %, lively movement at 100 %. Space adds reflections and depth. Focus keeps bass and hits in the centre.",
              "Charakter volí, jak šíře vzniká: čistá fáze na 0 %, přirozená dekorelace na 50 %, živý pohyb na 100 %. Prostor přidá odrazy a hloubku. Fokus drží basy a údery uprostřed.", { "p.easy_character", "p.easy_space", "p.easy_focus" }, {} },
            { "Under the hood shows the internal settings the macros are producing right now; hover any row to learn about it. Full controls opens the complete interface with exactly these settings, so you can continue by hand without any change in sound.",
              "Pod kapotou ukazuje vnitřní nastavení, která makra právě vytvářejí; najeďte na libovolný řádek a dozvíte se o něm víc. Všechny prvky otevřou úplné rozhraní přesně s těmito nastaveními, takže můžete pokračovat ručně bez jakékoli změny zvuku.", { "ui.easy" }, {} } } },
        { "Smart disable", "Chytré vypínání", {
            { "Modules that cannot affect the output are not computed: zero amount, or a silent input for longer than their tail.",
              "Moduly, které nemohou ovlivnit výstup, se nepočítají: nulové množství nebo ticho na vstupu delší než jejich doznívání.", { "card.spread" }, {} },
            { "Open Scopes and choose Activity in a lane: each row is a module, filled while it runs.",
              "Otevřete Průběhy a v jedné stopě zvolte Aktivitu: každý řádek je modul, vyplněný, dokud běží.", { "tab.scopes" }, {} },
            { "Stop playback or mute the input: modules fall asleep one by one as their tails end. The dot on each card goes dark. Sleeping changes nothing in the sound; it only saves processing.",
              "Zastavte přehrávání nebo ztlumte vstup: moduly usínají jeden po druhém, jak končí jejich doznívání. Tečka na každé kartě zhasne. Spánek nic nemění na zvuku, jen šetří výpočet.", { "card.spread", "card.velvet" }, {} } } },
    };
    return t;
}
} // namespace sph::ui
